import {
  CalendarDays,
  Dumbbell,
  FileSpreadsheet,
  Goal,
  ImageIcon,
  LayoutDashboard,
  Layers,
  ListOrdered,
  Package,
  Rocket,
  Settings,
  Shield,
  Trophy,
  UserCog,
  Users,
  Webhook,
  type LucideIcon,
} from 'lucide-react';
import type { TdTabKey } from '@/lib/td/navigation';

export const TD_TAB_ICONS: Record<TdTabKey, LucideIcon> = {
  dashboard: LayoutDashboard,
  'round-1': Layers,
  'round-2': ListOrdered,
  'round-3': Package,
  penalties: Goal,
  dailies: CalendarDays,
  practice: Dumbbell,
  clubs: Shield,
  media: ImageIcon,
  import: FileSpreadsheet,
  releases: Rocket,
  players: Users,
  leaderboard: Trophy,
  integration: Webhook,
  team: UserCog,
  settings: Settings,
};
