/* Table Derby admin contract v8. Generated by packages/contracts/scripts/emit-admin-contract.mjs from packages/contracts/src/admin.ts, adminContent.ts, adminOps.ts, adminReleases.ts and adminIntegration.ts; do not edit. Pin a copy and compare this version. */

export type AdminContractVersion = 8;

/** POST /admin/auth/login */
export type AdminLoginRequest = {
  email: string;
  password: string;
};

/** POST /admin/auth/refresh. One random requestId (a UUID) per refresh, kept for all its retries. */
export type AdminRefreshRequest = {
  refreshToken: string;
  requestId?: string;
};

/** POST /admin/auth/logout. Any refresh token of the session ends all of it. */
export type AdminLogoutRequest = {
  refreshToken: string;
};

/** POST /admin/auth/accept-invite */
export type AcceptInviteRequest = {
  token: string;
  password: string;
  name: string;
};

/** POST /admin/auth/reset */
export type PasswordResetRequest = {
  token: string;
  password: string;
};

/** POST /admin/auth/password (signed in). Ends every session of the member and returns a fresh one. */
export type PasswordChangeRequest = {
  current: string;
  next: string;
};

/** POST /admin/staff/invite. The API lower-cases the email; role "ops" passes the schema but is refused (403); an email still invited is invited again. */
export type StaffInviteRequest = {
  email: string;
  role: "editor" | "publisher" | "betsson_admin" | "ops";
  name?: string;
};

/** PATCH /admin/staff/:id. Role, status, or both; at least one. */
export type StaffPatchRequest = {
  role: "editor" | "publisher" | "betsson_admin" | "ops";
  status?: "active" | "disabled";
} | {
  role?: "editor" | "publisher" | "betsson_admin" | "ops";
  status: "active" | "disabled";
};

/** Login, refresh, accept-invite, reset and password change. expiresAt is the access token's expiry. */
export type AdminTokenResponse = {
  accessToken: string;
  refreshToken: string;
  expiresAt: string;
};

/** GET /admin/me */
export type Staff = {
  id: string;
  email: string;
  name: string;
  role: "editor" | "publisher" | "betsson_admin" | "ops";
};

/** One member of the team. */
export type StaffMember = {
  id: string;
  email: string;
  name: string;
  role: "editor" | "publisher" | "betsson_admin" | "ops";
  status: "invited" | "active" | "disabled";
  lastSignInAt: string | null;
};

/** GET /admin/staff */
export type StaffListResponse = {
  items: {
    id: string;
    email: string;
    name: string;
    role: "editor" | "publisher" | "betsson_admin" | "ops";
    status: "invited" | "active" | "disabled";
    lastSignInAt: string | null;
  }[];
};

/** A single-use link token (48 h) to hand over; never emailed by the API. */
export type LinkTokenResponse = {
  token: string;
  expiresAt: string;
};

/** POST /admin/staff/invite */
export type StaffInviteResponse = {
  token: string;
  expiresAt: string;
  member: {
    id: string;
    email: string;
    name: string;
    role: "editor" | "publisher" | "betsson_admin" | "ops";
    status: "invited" | "active" | "disabled";
    lastSignInAt: string | null;
  };
};

/** Every refusal. Branch on code; message is human text and may change. */
export type AdminError = {
  code: "invalid_request" | "invalid_credentials" | "invalid_refresh_token" | "refresh_token_reused" | "unauthorized" | "forbidden" | "not_found" | "rate_limited" | "invalid_token" | "weak_password" | "wrong_password" | "already_exists" | "conflict" | "busy" | "internal" | "revision_conflict" | "forbidden_transition" | "self_approval" | "validation" | "dependency_unapproved" | "in_use" | "conflict_retry" | "match_not_decided" | "same_result" | "too_close_to_midnight" | "invalid_image" | "too_large" | "storage_unavailable" | "publication_in_progress" | "idempotency_conflict" | "not_rollback_target" | "release_unrunnable";
  message: string;
  details?: unknown;
};

/** Round I categories: what an editor writes. */
export type CardCategoryData = {
  key: string;
  prompt: string;
};

/** Round I categories: a row as every /admin/content/card-categories route returns it. */
export type CardCategory = {
  id: string;
  status: "draft" | "ready" | "approved" | "archived";
  version: number;
  contentVersion: number;
  approvedVersion: number | null;
  position: number;
  approvedPosition: number | null;
  note: string;
  lastEditor: {
    id: string | null;
    name: string;
  };
  updatedBy: {
    id: string | null;
    name: string;
  };
  approvedBy: {
    id: string | null;
    name: string;
  } | null;
  approvedAt: string | null;
  createdAt: string;
  updatedAt: string;
  data: {
    key: string;
    prompt: string;
  };
  approved: {
    key: string;
    prompt: string;
  } | null;
};

/** GET /admin/content/card-categories: a page; pass nextCursor as cursor for the next. */
export type CardCategoryList = {
  items: {
    id: string;
    status: "draft" | "ready" | "approved" | "archived";
    version: number;
    contentVersion: number;
    approvedVersion: number | null;
    position: number;
    approvedPosition: number | null;
    note: string;
    lastEditor: {
      id: string | null;
      name: string;
    };
    updatedBy: {
      id: string | null;
      name: string;
    };
    approvedBy: {
      id: string | null;
      name: string;
    } | null;
    approvedAt: string | null;
    createdAt: string;
    updatedAt: string;
    data: {
      key: string;
      prompt: string;
    };
    approved: {
      key: string;
      prompt: string;
    } | null;
  }[];
  nextCursor: string | null;
};

/** POST /admin/content/card-categories: a draft, last in order unless a position is given. */
export type CardCategoryCreateRequest = {
  data: {
    key: string;
    prompt: string;
  };
  position?: number;
  note?: string;
};

/** PATCH /admin/content/card-categories/:id at the version read. Changed data or a changed position is a new content version (a ready or approved row goes back to draft); a note alone is not. */
export type CardCategoryEditRequest = {
  version: number;
  data: {
    key: string;
    prompt: string;
  };
  position?: number;
  note?: string;
};

/** Round I cards (approved with their category): what an editor writes. */
export type CardData = {
  categoryKey: string;
  key: string;
  value: 1 | 2 | 3;
  lines: string[];
  display: string;
  aliases: string[];
  photo: {
    id: number;
    ver: string;
  } | null;
  imageKey: string | null;
};

/** Round I cards (approved with their category): a row as every /admin/content/cards route returns it. */
export type Card = {
  id: string;
  status: "draft" | "ready" | "approved" | "archived";
  version: number;
  contentVersion: number;
  approvedVersion: number | null;
  position: number;
  approvedPosition: number | null;
  note: string;
  lastEditor: {
    id: string | null;
    name: string;
  };
  updatedBy: {
    id: string | null;
    name: string;
  };
  approvedBy: {
    id: string | null;
    name: string;
  } | null;
  approvedAt: string | null;
  createdAt: string;
  updatedAt: string;
  data: {
    categoryKey: string;
    key: string;
    value: 1 | 2 | 3;
    lines: string[];
    display: string;
    aliases: string[];
    photo: {
      id: number;
      ver: string;
    } | null;
    imageKey: string | null;
  };
  approved: {
    categoryKey: string;
    key: string;
    value: 1 | 2 | 3;
    lines: string[];
    display: string;
    aliases: string[];
    photo: {
      id: number;
      ver: string;
    } | null;
    imageKey: string | null;
  } | null;
};

/** GET /admin/content/cards: a page; pass nextCursor as cursor for the next. */
export type CardList = {
  items: {
    id: string;
    status: "draft" | "ready" | "approved" | "archived";
    version: number;
    contentVersion: number;
    approvedVersion: number | null;
    position: number;
    approvedPosition: number | null;
    note: string;
    lastEditor: {
      id: string | null;
      name: string;
    };
    updatedBy: {
      id: string | null;
      name: string;
    };
    approvedBy: {
      id: string | null;
      name: string;
    } | null;
    approvedAt: string | null;
    createdAt: string;
    updatedAt: string;
    data: {
      categoryKey: string;
      key: string;
      value: 1 | 2 | 3;
      lines: string[];
      display: string;
      aliases: string[];
      photo: {
        id: number;
        ver: string;
      } | null;
      imageKey: string | null;
    };
    approved: {
      categoryKey: string;
      key: string;
      value: 1 | 2 | 3;
      lines: string[];
      display: string;
      aliases: string[];
      photo: {
        id: number;
        ver: string;
      } | null;
      imageKey: string | null;
    } | null;
  }[];
  nextCursor: string | null;
};

/** POST /admin/content/cards: a draft, last in order unless a position is given. */
export type CardCreateRequest = {
  data: {
    categoryKey: string;
    key: string;
    value: 1 | 2 | 3;
    lines: string[];
    display: string;
    aliases: string[];
    photo: {
      id: number;
      ver: string;
    } | null;
    imageKey: string | null;
  };
  position?: number;
  note?: string;
};

/** PATCH /admin/content/cards/:id at the version read. Changed data or a changed position is a new content version (a ready or approved row goes back to draft); a note alone is not. */
export type CardEditRequest = {
  version: number;
  data: {
    categoryKey: string;
    key: string;
    value: 1 | 2 | 3;
    lines: string[];
    display: string;
    aliases: string[];
    photo: {
      id: number;
      ver: string;
    } | null;
    imageKey: string | null;
  };
  position?: number;
  note?: string;
};

/** Round II subjects: what an editor writes. */
export type WhoamiSubjectData = {
  key: string;
  display: string;
  aliases: string[];
  clues: string[];
};

/** Round II subjects: a row as every /admin/content/whoami-subjects route returns it. */
export type WhoamiSubject = {
  id: string;
  status: "draft" | "ready" | "approved" | "archived";
  version: number;
  contentVersion: number;
  approvedVersion: number | null;
  position: number;
  approvedPosition: number | null;
  note: string;
  lastEditor: {
    id: string | null;
    name: string;
  };
  updatedBy: {
    id: string | null;
    name: string;
  };
  approvedBy: {
    id: string | null;
    name: string;
  } | null;
  approvedAt: string | null;
  createdAt: string;
  updatedAt: string;
  data: {
    key: string;
    display: string;
    aliases: string[];
    clues: string[];
  };
  approved: {
    key: string;
    display: string;
    aliases: string[];
    clues: string[];
  } | null;
};

/** GET /admin/content/whoami-subjects: a page; pass nextCursor as cursor for the next. */
export type WhoamiSubjectList = {
  items: {
    id: string;
    status: "draft" | "ready" | "approved" | "archived";
    version: number;
    contentVersion: number;
    approvedVersion: number | null;
    position: number;
    approvedPosition: number | null;
    note: string;
    lastEditor: {
      id: string | null;
      name: string;
    };
    updatedBy: {
      id: string | null;
      name: string;
    };
    approvedBy: {
      id: string | null;
      name: string;
    } | null;
    approvedAt: string | null;
    createdAt: string;
    updatedAt: string;
    data: {
      key: string;
      display: string;
      aliases: string[];
      clues: string[];
    };
    approved: {
      key: string;
      display: string;
      aliases: string[];
      clues: string[];
    } | null;
  }[];
  nextCursor: string | null;
};

/** POST /admin/content/whoami-subjects: a draft, last in order unless a position is given. */
export type WhoamiSubjectCreateRequest = {
  data: {
    key: string;
    display: string;
    aliases: string[];
    clues: string[];
  };
  position?: number;
  note?: string;
};

/** PATCH /admin/content/whoami-subjects/:id at the version read. Changed data or a changed position is a new content version (a ready or approved row goes back to draft); a note alone is not. */
export type WhoamiSubjectEditRequest = {
  version: number;
  data: {
    key: string;
    display: string;
    aliases: string[];
    clues: string[];
  };
  position?: number;
  note?: string;
};

/** Round III categories: what an editor writes. */
export type BoxCategoryData = {
  key: string;
  title: string;
};

/** Round III categories: a row as every /admin/content/box-categories route returns it. */
export type BoxCategory = {
  id: string;
  status: "draft" | "ready" | "approved" | "archived";
  version: number;
  contentVersion: number;
  approvedVersion: number | null;
  position: number;
  approvedPosition: number | null;
  note: string;
  lastEditor: {
    id: string | null;
    name: string;
  };
  updatedBy: {
    id: string | null;
    name: string;
  };
  approvedBy: {
    id: string | null;
    name: string;
  } | null;
  approvedAt: string | null;
  createdAt: string;
  updatedAt: string;
  data: {
    key: string;
    title: string;
  };
  approved: {
    key: string;
    title: string;
  } | null;
};

/** GET /admin/content/box-categories: a page; pass nextCursor as cursor for the next. */
export type BoxCategoryList = {
  items: {
    id: string;
    status: "draft" | "ready" | "approved" | "archived";
    version: number;
    contentVersion: number;
    approvedVersion: number | null;
    position: number;
    approvedPosition: number | null;
    note: string;
    lastEditor: {
      id: string | null;
      name: string;
    };
    updatedBy: {
      id: string | null;
      name: string;
    };
    approvedBy: {
      id: string | null;
      name: string;
    } | null;
    approvedAt: string | null;
    createdAt: string;
    updatedAt: string;
    data: {
      key: string;
      title: string;
    };
    approved: {
      key: string;
      title: string;
    } | null;
  }[];
  nextCursor: string | null;
};

/** POST /admin/content/box-categories: a draft, last in order unless a position is given. */
export type BoxCategoryCreateRequest = {
  data: {
    key: string;
    title: string;
  };
  position?: number;
  note?: string;
};

/** PATCH /admin/content/box-categories/:id at the version read. Changed data or a changed position is a new content version (a ready or approved row goes back to draft); a note alone is not. */
export type BoxCategoryEditRequest = {
  version: number;
  data: {
    key: string;
    title: string;
  };
  position?: number;
  note?: string;
};

/** Round III questions (approved with their category): what an editor writes. */
export type BoxQuestionData = {
  categoryKey: string;
  key: string;
  q: string;
  display: string;
  aliases: string[];
};

/** Round III questions (approved with their category): a row as every /admin/content/box-questions route returns it. */
export type BoxQuestion = {
  id: string;
  status: "draft" | "ready" | "approved" | "archived";
  version: number;
  contentVersion: number;
  approvedVersion: number | null;
  position: number;
  approvedPosition: number | null;
  note: string;
  lastEditor: {
    id: string | null;
    name: string;
  };
  updatedBy: {
    id: string | null;
    name: string;
  };
  approvedBy: {
    id: string | null;
    name: string;
  } | null;
  approvedAt: string | null;
  createdAt: string;
  updatedAt: string;
  data: {
    categoryKey: string;
    key: string;
    q: string;
    display: string;
    aliases: string[];
  };
  approved: {
    categoryKey: string;
    key: string;
    q: string;
    display: string;
    aliases: string[];
  } | null;
};

/** GET /admin/content/box-questions: a page; pass nextCursor as cursor for the next. */
export type BoxQuestionList = {
  items: {
    id: string;
    status: "draft" | "ready" | "approved" | "archived";
    version: number;
    contentVersion: number;
    approvedVersion: number | null;
    position: number;
    approvedPosition: number | null;
    note: string;
    lastEditor: {
      id: string | null;
      name: string;
    };
    updatedBy: {
      id: string | null;
      name: string;
    };
    approvedBy: {
      id: string | null;
      name: string;
    } | null;
    approvedAt: string | null;
    createdAt: string;
    updatedAt: string;
    data: {
      categoryKey: string;
      key: string;
      q: string;
      display: string;
      aliases: string[];
    };
    approved: {
      categoryKey: string;
      key: string;
      q: string;
      display: string;
      aliases: string[];
    } | null;
  }[];
  nextCursor: string | null;
};

/** POST /admin/content/box-questions: a draft, last in order unless a position is given. */
export type BoxQuestionCreateRequest = {
  data: {
    categoryKey: string;
    key: string;
    q: string;
    display: string;
    aliases: string[];
  };
  position?: number;
  note?: string;
};

/** PATCH /admin/content/box-questions/:id at the version read. Changed data or a changed position is a new content version (a ready or approved row goes back to draft); a note alone is not. */
export type BoxQuestionEditRequest = {
  version: number;
  data: {
    categoryKey: string;
    key: string;
    q: string;
    display: string;
    aliases: string[];
  };
  position?: number;
  note?: string;
};

/** Penalty questions: what an editor writes. */
export type PenaltyQuestionData = {
  key: string;
  q: string;
  display: string;
  aliases: string[];
};

/** Penalty questions: a row as every /admin/content/penalty-questions route returns it. */
export type PenaltyQuestion = {
  id: string;
  status: "draft" | "ready" | "approved" | "archived";
  version: number;
  contentVersion: number;
  approvedVersion: number | null;
  position: number;
  approvedPosition: number | null;
  note: string;
  lastEditor: {
    id: string | null;
    name: string;
  };
  updatedBy: {
    id: string | null;
    name: string;
  };
  approvedBy: {
    id: string | null;
    name: string;
  } | null;
  approvedAt: string | null;
  createdAt: string;
  updatedAt: string;
  data: {
    key: string;
    q: string;
    display: string;
    aliases: string[];
  };
  approved: {
    key: string;
    q: string;
    display: string;
    aliases: string[];
  } | null;
};

/** GET /admin/content/penalty-questions: a page; pass nextCursor as cursor for the next. */
export type PenaltyQuestionList = {
  items: {
    id: string;
    status: "draft" | "ready" | "approved" | "archived";
    version: number;
    contentVersion: number;
    approvedVersion: number | null;
    position: number;
    approvedPosition: number | null;
    note: string;
    lastEditor: {
      id: string | null;
      name: string;
    };
    updatedBy: {
      id: string | null;
      name: string;
    };
    approvedBy: {
      id: string | null;
      name: string;
    } | null;
    approvedAt: string | null;
    createdAt: string;
    updatedAt: string;
    data: {
      key: string;
      q: string;
      display: string;
      aliases: string[];
    };
    approved: {
      key: string;
      q: string;
      display: string;
      aliases: string[];
    } | null;
  }[];
  nextCursor: string | null;
};

/** POST /admin/content/penalty-questions: a draft, last in order unless a position is given. */
export type PenaltyQuestionCreateRequest = {
  data: {
    key: string;
    q: string;
    display: string;
    aliases: string[];
  };
  position?: number;
  note?: string;
};

/** PATCH /admin/content/penalty-questions/:id at the version read. Changed data or a changed position is a new content version (a ready or approved row goes back to draft); a note alone is not. */
export type PenaltyQuestionEditRequest = {
  version: number;
  data: {
    key: string;
    q: string;
    display: string;
    aliases: string[];
  };
  position?: number;
  note?: string;
};

/** Practice: what an editor writes. */
export type PracticeQuestionData = {
  key: string;
  difficulty: "easy" | "medium" | "hard";
  category: string;
  prompt: string;
  options: string[];
  answer: number;
  explanation: string | null;
  imageKey: string | null;
};

/** Practice: a row as every /admin/content/practice-questions route returns it. */
export type PracticeQuestion = {
  id: string;
  status: "draft" | "ready" | "approved" | "archived";
  version: number;
  contentVersion: number;
  approvedVersion: number | null;
  position: number;
  approvedPosition: number | null;
  note: string;
  lastEditor: {
    id: string | null;
    name: string;
  };
  updatedBy: {
    id: string | null;
    name: string;
  };
  approvedBy: {
    id: string | null;
    name: string;
  } | null;
  approvedAt: string | null;
  createdAt: string;
  updatedAt: string;
  data: {
    key: string;
    difficulty: "easy" | "medium" | "hard";
    category: string;
    prompt: string;
    options: string[];
    answer: number;
    explanation: string | null;
    imageKey: string | null;
  };
  approved: {
    key: string;
    difficulty: "easy" | "medium" | "hard";
    category: string;
    prompt: string;
    options: string[];
    answer: number;
    explanation: string | null;
    imageKey: string | null;
  } | null;
};

/** GET /admin/content/practice-questions: a page; pass nextCursor as cursor for the next. */
export type PracticeQuestionList = {
  items: {
    id: string;
    status: "draft" | "ready" | "approved" | "archived";
    version: number;
    contentVersion: number;
    approvedVersion: number | null;
    position: number;
    approvedPosition: number | null;
    note: string;
    lastEditor: {
      id: string | null;
      name: string;
    };
    updatedBy: {
      id: string | null;
      name: string;
    };
    approvedBy: {
      id: string | null;
      name: string;
    } | null;
    approvedAt: string | null;
    createdAt: string;
    updatedAt: string;
    data: {
      key: string;
      difficulty: "easy" | "medium" | "hard";
      category: string;
      prompt: string;
      options: string[];
      answer: number;
      explanation: string | null;
      imageKey: string | null;
    };
    approved: {
      key: string;
      difficulty: "easy" | "medium" | "hard";
      category: string;
      prompt: string;
      options: string[];
      answer: number;
      explanation: string | null;
      imageKey: string | null;
    } | null;
  }[];
  nextCursor: string | null;
};

/** POST /admin/content/practice-questions: a draft, last in order unless a position is given. */
export type PracticeQuestionCreateRequest = {
  data: {
    key: string;
    difficulty: "easy" | "medium" | "hard";
    category: string;
    prompt: string;
    options: string[];
    answer: number;
    explanation: string | null;
    imageKey: string | null;
  };
  position?: number;
  note?: string;
};

/** PATCH /admin/content/practice-questions/:id at the version read. Changed data or a changed position is a new content version (a ready or approved row goes back to draft); a note alone is not. */
export type PracticeQuestionEditRequest = {
  version: number;
  data: {
    key: string;
    difficulty: "easy" | "medium" | "hard";
    category: string;
    prompt: string;
    options: string[];
    answer: number;
    explanation: string | null;
    imageKey: string | null;
  };
  position?: number;
  note?: string;
};

/** Images (credit, licence and source optional): exactly one of uploadId (an upload) and url (an image kept from before), the other null: what an editor writes. */
export type MediaData = {
  key: string;
  url: null;
  uploadId: string;
  width: number;
  height: number;
  author: string | null;
  license: string | null;
  source: string | null;
} | {
  key: string;
  url: string;
  uploadId: null;
  width: number;
  height: number;
  author: string | null;
  license: string | null;
  source: string | null;
};

/** Images (credit, licence and source optional): exactly one of uploadId (an upload) and url (an image kept from before), the other null: a row as every /admin/content/media route returns it. */
export type Media = {
  id: string;
  status: "draft" | "ready" | "approved" | "archived";
  version: number;
  contentVersion: number;
  approvedVersion: number | null;
  position: number;
  approvedPosition: number | null;
  note: string;
  lastEditor: {
    id: string | null;
    name: string;
  };
  updatedBy: {
    id: string | null;
    name: string;
  };
  approvedBy: {
    id: string | null;
    name: string;
  } | null;
  approvedAt: string | null;
  createdAt: string;
  updatedAt: string;
  data: {
    key: string;
    url: null;
    uploadId: string;
    width: number;
    height: number;
    author: string | null;
    license: string | null;
    source: string | null;
  } | {
    key: string;
    url: string;
    uploadId: null;
    width: number;
    height: number;
    author: string | null;
    license: string | null;
    source: string | null;
  };
  approved: {
    key: string;
    url: null;
    uploadId: string;
    width: number;
    height: number;
    author: string | null;
    license: string | null;
    source: string | null;
  } | {
    key: string;
    url: string;
    uploadId: null;
    width: number;
    height: number;
    author: string | null;
    license: string | null;
    source: string | null;
  } | null;
};

/** GET /admin/content/media: a page; pass nextCursor as cursor for the next. */
export type MediaList = {
  items: {
    id: string;
    status: "draft" | "ready" | "approved" | "archived";
    version: number;
    contentVersion: number;
    approvedVersion: number | null;
    position: number;
    approvedPosition: number | null;
    note: string;
    lastEditor: {
      id: string | null;
      name: string;
    };
    updatedBy: {
      id: string | null;
      name: string;
    };
    approvedBy: {
      id: string | null;
      name: string;
    } | null;
    approvedAt: string | null;
    createdAt: string;
    updatedAt: string;
    data: {
      key: string;
      url: null;
      uploadId: string;
      width: number;
      height: number;
      author: string | null;
      license: string | null;
      source: string | null;
    } | {
      key: string;
      url: string;
      uploadId: null;
      width: number;
      height: number;
      author: string | null;
      license: string | null;
      source: string | null;
    };
    approved: {
      key: string;
      url: null;
      uploadId: string;
      width: number;
      height: number;
      author: string | null;
      license: string | null;
      source: string | null;
    } | {
      key: string;
      url: string;
      uploadId: null;
      width: number;
      height: number;
      author: string | null;
      license: string | null;
      source: string | null;
    } | null;
  }[];
  nextCursor: string | null;
};

/** POST /admin/content/media: a draft, last in order unless a position is given. */
export type MediaCreateRequest = {
  data: {
    key: string;
    url: null;
    uploadId: string;
    width: number;
    height: number;
    author: string | null;
    license: string | null;
    source: string | null;
  } | {
    key: string;
    url: string;
    uploadId: null;
    width: number;
    height: number;
    author: string | null;
    license: string | null;
    source: string | null;
  };
  position?: number;
  note?: string;
};

/** PATCH /admin/content/media/:id at the version read. Changed data or a changed position is a new content version (a ready or approved row goes back to draft); a note alone is not. */
export type MediaEditRequest = {
  version: number;
  data: {
    key: string;
    url: null;
    uploadId: string;
    width: number;
    height: number;
    author: string | null;
    license: string | null;
    source: string | null;
  } | {
    key: string;
    url: string;
    uploadId: null;
    width: number;
    height: number;
    author: string | null;
    license: string | null;
    source: string | null;
  };
  position?: number;
  note?: string;
};

/** Clubs and crests: what an editor writes. */
export type ClubData = {
  key: string;
  label: string;
  value: string;
  country: string;
  countryKa: string | null;
  flag: string | null;
  crest: string;
  crestImageKey: string | null;
  hidden: boolean;
};

/** Clubs and crests: a row as every /admin/content/clubs route returns it. */
export type Club = {
  id: string;
  status: "draft" | "ready" | "approved" | "archived";
  version: number;
  contentVersion: number;
  approvedVersion: number | null;
  position: number;
  approvedPosition: number | null;
  note: string;
  lastEditor: {
    id: string | null;
    name: string;
  };
  updatedBy: {
    id: string | null;
    name: string;
  };
  approvedBy: {
    id: string | null;
    name: string;
  } | null;
  approvedAt: string | null;
  createdAt: string;
  updatedAt: string;
  data: {
    key: string;
    label: string;
    value: string;
    country: string;
    countryKa: string | null;
    flag: string | null;
    crest: string;
    crestImageKey: string | null;
    hidden: boolean;
  };
  approved: {
    key: string;
    label: string;
    value: string;
    country: string;
    countryKa: string | null;
    flag: string | null;
    crest: string;
    crestImageKey: string | null;
    hidden: boolean;
  } | null;
};

/** GET /admin/content/clubs: a page; pass nextCursor as cursor for the next. */
export type ClubList = {
  items: {
    id: string;
    status: "draft" | "ready" | "approved" | "archived";
    version: number;
    contentVersion: number;
    approvedVersion: number | null;
    position: number;
    approvedPosition: number | null;
    note: string;
    lastEditor: {
      id: string | null;
      name: string;
    };
    updatedBy: {
      id: string | null;
      name: string;
    };
    approvedBy: {
      id: string | null;
      name: string;
    } | null;
    approvedAt: string | null;
    createdAt: string;
    updatedAt: string;
    data: {
      key: string;
      label: string;
      value: string;
      country: string;
      countryKa: string | null;
      flag: string | null;
      crest: string;
      crestImageKey: string | null;
      hidden: boolean;
    };
    approved: {
      key: string;
      label: string;
      value: string;
      country: string;
      countryKa: string | null;
      flag: string | null;
      crest: string;
      crestImageKey: string | null;
      hidden: boolean;
    } | null;
  }[];
  nextCursor: string | null;
};

/** POST /admin/content/clubs: a draft, last in order unless a position is given. */
export type ClubCreateRequest = {
  data: {
    key: string;
    label: string;
    value: string;
    country: string;
    countryKa: string | null;
    flag: string | null;
    crest: string;
    crestImageKey: string | null;
    hidden: boolean;
  };
  position?: number;
  note?: string;
};

/** PATCH /admin/content/clubs/:id at the version read. Changed data or a changed position is a new content version (a ready or approved row goes back to draft); a note alone is not. */
export type ClubEditRequest = {
  version: number;
  data: {
    key: string;
    label: string;
    value: string;
    country: string;
    countryKa: string | null;
    flag: string | null;
    crest: string;
    crestImageKey: string | null;
    hidden: boolean;
  };
  position?: number;
  note?: string;
};

/** Football Logic questions: what an editor writes. */
export type FootballLogicData = {
  key: string;
  puzzle: string;
  category: string;
  prompt: string;
  imageA: string | null;
  imageB: string | null;
  displayAnswer: string;
  acceptedAnswers: string[];
};

/** Football Logic questions: a row as every /admin/content/football-logic route returns it. */
export type FootballLogic = {
  id: string;
  status: "draft" | "ready" | "approved" | "archived";
  version: number;
  contentVersion: number;
  approvedVersion: number | null;
  position: number;
  approvedPosition: number | null;
  note: string;
  lastEditor: {
    id: string | null;
    name: string;
  };
  updatedBy: {
    id: string | null;
    name: string;
  };
  approvedBy: {
    id: string | null;
    name: string;
  } | null;
  approvedAt: string | null;
  createdAt: string;
  updatedAt: string;
  data: {
    key: string;
    puzzle: string;
    category: string;
    prompt: string;
    imageA: string | null;
    imageB: string | null;
    displayAnswer: string;
    acceptedAnswers: string[];
  };
  approved: {
    key: string;
    puzzle: string;
    category: string;
    prompt: string;
    imageA: string | null;
    imageB: string | null;
    displayAnswer: string;
    acceptedAnswers: string[];
  } | null;
};

/** GET /admin/content/football-logic: a page; pass nextCursor as cursor for the next. */
export type FootballLogicList = {
  items: {
    id: string;
    status: "draft" | "ready" | "approved" | "archived";
    version: number;
    contentVersion: number;
    approvedVersion: number | null;
    position: number;
    approvedPosition: number | null;
    note: string;
    lastEditor: {
      id: string | null;
      name: string;
    };
    updatedBy: {
      id: string | null;
      name: string;
    };
    approvedBy: {
      id: string | null;
      name: string;
    } | null;
    approvedAt: string | null;
    createdAt: string;
    updatedAt: string;
    data: {
      key: string;
      puzzle: string;
      category: string;
      prompt: string;
      imageA: string | null;
      imageB: string | null;
      displayAnswer: string;
      acceptedAnswers: string[];
    };
    approved: {
      key: string;
      puzzle: string;
      category: string;
      prompt: string;
      imageA: string | null;
      imageB: string | null;
      displayAnswer: string;
      acceptedAnswers: string[];
    } | null;
  }[];
  nextCursor: string | null;
};

/** POST /admin/content/football-logic: a draft, last in order unless a position is given. */
export type FootballLogicCreateRequest = {
  data: {
    key: string;
    puzzle: string;
    category: string;
    prompt: string;
    imageA: string | null;
    imageB: string | null;
    displayAnswer: string;
    acceptedAnswers: string[];
  };
  position?: number;
  note?: string;
};

/** PATCH /admin/content/football-logic/:id at the version read. Changed data or a changed position is a new content version (a ready or approved row goes back to draft); a note alone is not. */
export type FootballLogicEditRequest = {
  version: number;
  data: {
    key: string;
    puzzle: string;
    category: string;
    prompt: string;
    imageA: string | null;
    imageB: string | null;
    displayAnswer: string;
    acceptedAnswers: string[];
  };
  position?: number;
  note?: string;
};

/** Put in Order rounds: what an editor writes. */
export type PutInOrderData = {
  key: string;
  puzzle: string;
  prompt: string;
  items: {
    key: string;
    label: string;
    sortValue: number;
  }[];
};

/** Put in Order rounds: a row as every /admin/content/put-in-order route returns it. */
export type PutInOrder = {
  id: string;
  status: "draft" | "ready" | "approved" | "archived";
  version: number;
  contentVersion: number;
  approvedVersion: number | null;
  position: number;
  approvedPosition: number | null;
  note: string;
  lastEditor: {
    id: string | null;
    name: string;
  };
  updatedBy: {
    id: string | null;
    name: string;
  };
  approvedBy: {
    id: string | null;
    name: string;
  } | null;
  approvedAt: string | null;
  createdAt: string;
  updatedAt: string;
  data: {
    key: string;
    puzzle: string;
    prompt: string;
    items: {
      key: string;
      label: string;
      sortValue: number;
    }[];
  };
  approved: {
    key: string;
    puzzle: string;
    prompt: string;
    items: {
      key: string;
      label: string;
      sortValue: number;
    }[];
  } | null;
};

/** GET /admin/content/put-in-order: a page; pass nextCursor as cursor for the next. */
export type PutInOrderList = {
  items: {
    id: string;
    status: "draft" | "ready" | "approved" | "archived";
    version: number;
    contentVersion: number;
    approvedVersion: number | null;
    position: number;
    approvedPosition: number | null;
    note: string;
    lastEditor: {
      id: string | null;
      name: string;
    };
    updatedBy: {
      id: string | null;
      name: string;
    };
    approvedBy: {
      id: string | null;
      name: string;
    } | null;
    approvedAt: string | null;
    createdAt: string;
    updatedAt: string;
    data: {
      key: string;
      puzzle: string;
      prompt: string;
      items: {
        key: string;
        label: string;
        sortValue: number;
      }[];
    };
    approved: {
      key: string;
      puzzle: string;
      prompt: string;
      items: {
        key: string;
        label: string;
        sortValue: number;
      }[];
    } | null;
  }[];
  nextCursor: string | null;
};

/** POST /admin/content/put-in-order: a draft, last in order unless a position is given. */
export type PutInOrderCreateRequest = {
  data: {
    key: string;
    puzzle: string;
    prompt: string;
    items: {
      key: string;
      label: string;
      sortValue: number;
    }[];
  };
  position?: number;
  note?: string;
};

/** PATCH /admin/content/put-in-order/:id at the version read. Changed data or a changed position is a new content version (a ready or approved row goes back to draft); a note alone is not. */
export type PutInOrderEditRequest = {
  version: number;
  data: {
    key: string;
    puzzle: string;
    prompt: string;
    items: {
      key: string;
      label: string;
      sortValue: number;
    }[];
  };
  position?: number;
  note?: string;
};

/** Career Path questions: what an editor writes. */
export type CareerPathData = {
  key: string;
  puzzle: string;
  prompt: string;
  displayAnswer: string;
  acceptedAnswers: string[];
  clubs: {
    name: string;
    clubKey: string | null;
  }[];
};

/** Career Path questions: a row as every /admin/content/career-path route returns it. */
export type CareerPath = {
  id: string;
  status: "draft" | "ready" | "approved" | "archived";
  version: number;
  contentVersion: number;
  approvedVersion: number | null;
  position: number;
  approvedPosition: number | null;
  note: string;
  lastEditor: {
    id: string | null;
    name: string;
  };
  updatedBy: {
    id: string | null;
    name: string;
  };
  approvedBy: {
    id: string | null;
    name: string;
  } | null;
  approvedAt: string | null;
  createdAt: string;
  updatedAt: string;
  data: {
    key: string;
    puzzle: string;
    prompt: string;
    displayAnswer: string;
    acceptedAnswers: string[];
    clubs: {
      name: string;
      clubKey: string | null;
    }[];
  };
  approved: {
    key: string;
    puzzle: string;
    prompt: string;
    displayAnswer: string;
    acceptedAnswers: string[];
    clubs: {
      name: string;
      clubKey: string | null;
    }[];
  } | null;
};

/** GET /admin/content/career-path: a page; pass nextCursor as cursor for the next. */
export type CareerPathList = {
  items: {
    id: string;
    status: "draft" | "ready" | "approved" | "archived";
    version: number;
    contentVersion: number;
    approvedVersion: number | null;
    position: number;
    approvedPosition: number | null;
    note: string;
    lastEditor: {
      id: string | null;
      name: string;
    };
    updatedBy: {
      id: string | null;
      name: string;
    };
    approvedBy: {
      id: string | null;
      name: string;
    } | null;
    approvedAt: string | null;
    createdAt: string;
    updatedAt: string;
    data: {
      key: string;
      puzzle: string;
      prompt: string;
      displayAnswer: string;
      acceptedAnswers: string[];
      clubs: {
        name: string;
        clubKey: string | null;
      }[];
    };
    approved: {
      key: string;
      puzzle: string;
      prompt: string;
      displayAnswer: string;
      acceptedAnswers: string[];
      clubs: {
        name: string;
        clubKey: string | null;
      }[];
    } | null;
  }[];
  nextCursor: string | null;
};

/** POST /admin/content/career-path: a draft, last in order unless a position is given. */
export type CareerPathCreateRequest = {
  data: {
    key: string;
    puzzle: string;
    prompt: string;
    displayAnswer: string;
    acceptedAnswers: string[];
    clubs: {
      name: string;
      clubKey: string | null;
    }[];
  };
  position?: number;
  note?: string;
};

/** PATCH /admin/content/career-path/:id at the version read. Changed data or a changed position is a new content version (a ready or approved row goes back to draft); a note alone is not. */
export type CareerPathEditRequest = {
  version: number;
  data: {
    key: string;
    puzzle: string;
    prompt: string;
    displayAnswer: string;
    acceptedAnswers: string[];
    clubs: {
      name: string;
      clubKey: string | null;
    }[];
  };
  position?: number;
  note?: string;
};

/** The dailies calendar: what an editor writes. */
export type DailyScheduleData = {
  game: "footballLogic" | "putInOrder" | "careerPath";
  date: string;
  puzzle: string;
};

/** The dailies calendar: a row as every /admin/content/daily-schedule route returns it. */
export type DailySchedule = {
  id: string;
  status: "draft" | "ready" | "approved" | "archived";
  version: number;
  contentVersion: number;
  approvedVersion: number | null;
  position: number;
  approvedPosition: number | null;
  note: string;
  lastEditor: {
    id: string | null;
    name: string;
  };
  updatedBy: {
    id: string | null;
    name: string;
  };
  approvedBy: {
    id: string | null;
    name: string;
  } | null;
  approvedAt: string | null;
  createdAt: string;
  updatedAt: string;
  data: {
    game: "footballLogic" | "putInOrder" | "careerPath";
    date: string;
    puzzle: string;
  };
  approved: {
    game: "footballLogic" | "putInOrder" | "careerPath";
    date: string;
    puzzle: string;
  } | null;
};

/** GET /admin/content/daily-schedule: a page; pass nextCursor as cursor for the next. */
export type DailyScheduleList = {
  items: {
    id: string;
    status: "draft" | "ready" | "approved" | "archived";
    version: number;
    contentVersion: number;
    approvedVersion: number | null;
    position: number;
    approvedPosition: number | null;
    note: string;
    lastEditor: {
      id: string | null;
      name: string;
    };
    updatedBy: {
      id: string | null;
      name: string;
    };
    approvedBy: {
      id: string | null;
      name: string;
    } | null;
    approvedAt: string | null;
    createdAt: string;
    updatedAt: string;
    data: {
      game: "footballLogic" | "putInOrder" | "careerPath";
      date: string;
      puzzle: string;
    };
    approved: {
      game: "footballLogic" | "putInOrder" | "careerPath";
      date: string;
      puzzle: string;
    } | null;
  }[];
  nextCursor: string | null;
};

/** POST /admin/content/daily-schedule: a draft, last in order unless a position is given. */
export type DailyScheduleCreateRequest = {
  data: {
    game: "footballLogic" | "putInOrder" | "careerPath";
    date: string;
    puzzle: string;
  };
  position?: number;
  note?: string;
};

/** PATCH /admin/content/daily-schedule/:id at the version read. Changed data or a changed position is a new content version (a ready or approved row goes back to draft); a note alone is not. */
export type DailyScheduleEditRequest = {
  version: number;
  data: {
    game: "footballLogic" | "putInOrder" | "careerPath";
    date: string;
    puzzle: string;
  };
  position?: number;
  note?: string;
};

/** Dailies timing and cycle: what an editor writes. */
export type DailySettingsData = {
  game: "footballLogic" | "putInOrder" | "careerPath";
  seconds: number | null;
  cycle: {
    anchor: string;
    sets: string[];
  } | null;
};

/** Dailies timing and cycle: a row as every /admin/content/daily-settings route returns it. */
export type DailySettings = {
  id: string;
  status: "draft" | "ready" | "approved" | "archived";
  version: number;
  contentVersion: number;
  approvedVersion: number | null;
  position: number;
  approvedPosition: number | null;
  note: string;
  lastEditor: {
    id: string | null;
    name: string;
  };
  updatedBy: {
    id: string | null;
    name: string;
  };
  approvedBy: {
    id: string | null;
    name: string;
  } | null;
  approvedAt: string | null;
  createdAt: string;
  updatedAt: string;
  data: {
    game: "footballLogic" | "putInOrder" | "careerPath";
    seconds: number | null;
    cycle: {
      anchor: string;
      sets: string[];
    } | null;
  };
  approved: {
    game: "footballLogic" | "putInOrder" | "careerPath";
    seconds: number | null;
    cycle: {
      anchor: string;
      sets: string[];
    } | null;
  } | null;
};

/** GET /admin/content/daily-settings: a page; pass nextCursor as cursor for the next. */
export type DailySettingsList = {
  items: {
    id: string;
    status: "draft" | "ready" | "approved" | "archived";
    version: number;
    contentVersion: number;
    approvedVersion: number | null;
    position: number;
    approvedPosition: number | null;
    note: string;
    lastEditor: {
      id: string | null;
      name: string;
    };
    updatedBy: {
      id: string | null;
      name: string;
    };
    approvedBy: {
      id: string | null;
      name: string;
    } | null;
    approvedAt: string | null;
    createdAt: string;
    updatedAt: string;
    data: {
      game: "footballLogic" | "putInOrder" | "careerPath";
      seconds: number | null;
      cycle: {
        anchor: string;
        sets: string[];
      } | null;
    };
    approved: {
      game: "footballLogic" | "putInOrder" | "careerPath";
      seconds: number | null;
      cycle: {
        anchor: string;
        sets: string[];
      } | null;
    } | null;
  }[];
  nextCursor: string | null;
};

/** POST /admin/content/daily-settings: a draft, last in order unless a position is given. */
export type DailySettingsCreateRequest = {
  data: {
    game: "footballLogic" | "putInOrder" | "careerPath";
    seconds: number | null;
    cycle: {
      anchor: string;
      sets: string[];
    } | null;
  };
  position?: number;
  note?: string;
};

/** PATCH /admin/content/daily-settings/:id at the version read. Changed data or a changed position is a new content version (a ready or approved row goes back to draft); a note alone is not. */
export type DailySettingsEditRequest = {
  version: number;
  data: {
    game: "footballLogic" | "putInOrder" | "careerPath";
    seconds: number | null;
    cycle: {
      anchor: string;
      sets: string[];
    } | null;
  };
  position?: number;
  note?: string;
};

/** A member, or the system (id null: the seed). */
export type ContentActor = {
  id: string | null;
  name: string;
};

/** The query of every content list: status (a comma list; default all but archived), q (text search), category (a category key for cards and box questions, the label for practice and Football Logic), puzzle, game, from and to (the calendar), sort (natural, updated, created), dir, cursor, limit (1–200, default 50). */
export type ContentListQuery = {
  status?: string;
  q?: string;
  category?: string;
  puzzle?: string;
  game?: "footballLogic" | "putInOrder" | "careerPath";
  from?: string;
  to?: string;
  sort?: "natural" | "updated" | "created";
  dir?: "asc" | "desc";
  cursor?: string;
  limit?: string;
};

/** The query of the import list and of a row history: cursor, limit (1–200, default 50). */
export type ContentPageQuery = {
  cursor?: string;
  limit?: string;
};

/** GET /admin/content/:type/:id/history: a row's changes, newest first (by the id of its trail entry). Rows an import undo removed keep their history. */
export type ContentHistory = {
  items: {
    id: string;
    at: string;
    actor: {
      id: string | null;
      name: string;
    };
    action: "create" | "edit" | "edit.note" | "ready" | "approve" | "archive" | "restore" | "delete" | "seed";
    fromStatus: "draft" | "ready" | "approved" | "archived" | null;
    toStatus: "draft" | "ready" | "approved" | "archived" | null;
    version: number | null;
    contentVersion: number | null;
    batchId: string | null;
  }[];
  nextCursor: string | null;
};

/** Mark ready, archive, restore: at the version read. */
export type ContentTransitionRequest = {
  version: number;
};

/** Approve at the version read. A category approves the listed cards (or questions) with it, at their versions; every other live one must be approved already. */
export type ContentApproveRequest = {
  version: number;
  children?: {
    id: string;
    version: number;
  }[];
};

/** One import item: a row of a type, created as a draft. Rows refer to rows before them by key. */
export type ContentImportItem = {
  type: "card-categories";
  data: {
    key: string;
    prompt: string;
  };
  position?: number;
  note?: string;
} | {
  type: "cards";
  data: {
    categoryKey: string;
    key: string;
    value: 1 | 2 | 3;
    lines: string[];
    display: string;
    aliases: string[];
    photo: {
      id: number;
      ver: string;
    } | null;
    imageKey: string | null;
  };
  position?: number;
  note?: string;
} | {
  type: "whoami-subjects";
  data: {
    key: string;
    display: string;
    aliases: string[];
    clues: string[];
  };
  position?: number;
  note?: string;
} | {
  type: "box-categories";
  data: {
    key: string;
    title: string;
  };
  position?: number;
  note?: string;
} | {
  type: "box-questions";
  data: {
    categoryKey: string;
    key: string;
    q: string;
    display: string;
    aliases: string[];
  };
  position?: number;
  note?: string;
} | {
  type: "penalty-questions";
  data: {
    key: string;
    q: string;
    display: string;
    aliases: string[];
  };
  position?: number;
  note?: string;
} | {
  type: "practice-questions";
  data: {
    key: string;
    difficulty: "easy" | "medium" | "hard";
    category: string;
    prompt: string;
    options: string[];
    answer: number;
    explanation: string | null;
    imageKey: string | null;
  };
  position?: number;
  note?: string;
} | {
  type: "media";
  data: {
    key: string;
    url: null;
    uploadId: string;
    width: number;
    height: number;
    author: string | null;
    license: string | null;
    source: string | null;
  } | {
    key: string;
    url: string;
    uploadId: null;
    width: number;
    height: number;
    author: string | null;
    license: string | null;
    source: string | null;
  };
  position?: number;
  note?: string;
} | {
  type: "clubs";
  data: {
    key: string;
    label: string;
    value: string;
    country: string;
    countryKa: string | null;
    flag: string | null;
    crest: string;
    crestImageKey: string | null;
    hidden: boolean;
  };
  position?: number;
  note?: string;
} | {
  type: "football-logic";
  data: {
    key: string;
    puzzle: string;
    category: string;
    prompt: string;
    imageA: string | null;
    imageB: string | null;
    displayAnswer: string;
    acceptedAnswers: string[];
  };
  position?: number;
  note?: string;
} | {
  type: "put-in-order";
  data: {
    key: string;
    puzzle: string;
    prompt: string;
    items: {
      key: string;
      label: string;
      sortValue: number;
    }[];
  };
  position?: number;
  note?: string;
} | {
  type: "career-path";
  data: {
    key: string;
    puzzle: string;
    prompt: string;
    displayAnswer: string;
    acceptedAnswers: string[];
    clubs: {
      name: string;
      clubKey: string | null;
    }[];
  };
  position?: number;
  note?: string;
} | {
  type: "daily-schedule";
  data: {
    game: "footballLogic" | "putInOrder" | "careerPath";
    date: string;
    puzzle: string;
  };
  position?: number;
  note?: string;
} | {
  type: "daily-settings";
  data: {
    game: "footballLogic" | "putInOrder" | "careerPath";
    seconds: number | null;
    cycle: {
      anchor: string;
      sets: string[];
    } | null;
  };
  position?: number;
  note?: string;
};

/** POST /admin/content/imports/preview: items as ContentImportItem, each judged on its own. */
export type ContentImportPreviewRequest = {
  items: unknown[];
};

/** POST /admin/content/imports: the previewed items under a key the client chose (the same key with the same items is the same import; with other items, 409 conflict). */
export type ContentImportRequest = {
  batchKey: string;
  items: unknown[];
};

/** What an import would do, item by item (preview; the details of a refused import). */
export type ContentImportReport = {
  payloadHash: string;
  counts: {
    items: number;
    create: number;
    error: number;
  };
  rows: {
    index: number;
    type: string;
    label: string | null;
    action: "create" | "error";
    issues: {
      code: "invalid" | "duplicate" | "duplicate_in_batch" | "missing_reference" | "rule";
      message: string;
      path: string;
    }[];
  }[];
};

/** An import batch, without its rows. */
export type ContentImportBatchSummary = {
  id: string;
  batchKey: string;
  status: "applied" | "partly_undone" | "undone";
  itemCount: number;
  createdBy: {
    id: string | null;
    name: string;
  };
  createdAt: string;
  undoneAt: string | null;
  undoneBy: {
    id: string | null;
    name: string;
  } | null;
  counts: {
    created: number;
    removed: number;
    kept: number;
  };
};

/** An import batch and the rows it created, in item order. Undo removes rows still at the version it created and never approved; it keeps the others and says why. */
export type ContentImportBatch = {
  id: string;
  batchKey: string;
  status: "applied" | "partly_undone" | "undone";
  itemCount: number;
  createdBy: {
    id: string | null;
    name: string;
  };
  createdAt: string;
  undoneAt: string | null;
  undoneBy: {
    id: string | null;
    name: string;
  } | null;
  counts: {
    created: number;
    removed: number;
    kept: number;
  };
  rows: {
    index: number;
    type: "card-categories" | "cards" | "whoami-subjects" | "box-categories" | "box-questions" | "penalty-questions" | "practice-questions" | "media" | "clubs" | "football-logic" | "put-in-order" | "career-path" | "daily-schedule" | "daily-settings";
    id: string;
    label: string;
    contentVersion: number;
    outcome: "created" | "removed" | "kept";
    reason: "edited" | "approved" | "referenced" | "published" | null;
  }[];
};

/** POST /admin/content/imports: created is false when the key was applied before. */
export type ContentImportResult = {
  created: boolean;
  batch: {
    id: string;
    batchKey: string;
    status: "applied" | "partly_undone" | "undone";
    itemCount: number;
    createdBy: {
      id: string | null;
      name: string;
    };
    createdAt: string;
    undoneAt: string | null;
    undoneBy: {
      id: string | null;
      name: string;
    } | null;
    counts: {
      created: number;
      removed: number;
      kept: number;
    };
    rows: {
      index: number;
      type: "card-categories" | "cards" | "whoami-subjects" | "box-categories" | "box-questions" | "penalty-questions" | "practice-questions" | "media" | "clubs" | "football-logic" | "put-in-order" | "career-path" | "daily-schedule" | "daily-settings";
      id: string;
      label: string;
      contentVersion: number;
      outcome: "created" | "removed" | "kept";
      reason: "edited" | "approved" | "referenced" | "published" | null;
    }[];
  };
};

/** GET /admin/content/imports: newest first. */
export type ContentImportBatchList = {
  items: {
    id: string;
    batchKey: string;
    status: "applied" | "partly_undone" | "undone";
    itemCount: number;
    createdBy: {
      id: string | null;
      name: string;
    };
    createdAt: string;
    undoneAt: string | null;
    undoneBy: {
      id: string | null;
      name: string;
    } | null;
    counts: {
      created: number;
      removed: number;
      kept: number;
    };
  }[];
  nextCursor: string | null;
};

/** details of 409 revision_conflict: the row as it is now (as GET returns it), and the listed child whose version moved, if one did. */
export type RevisionConflictDetails = {
  current: unknown;
  child?: {
    type: "card-categories" | "cards" | "whoami-subjects" | "box-categories" | "box-questions" | "penalty-questions" | "practice-questions" | "media" | "clubs" | "football-logic" | "put-in-order" | "career-path" | "daily-schedule" | "daily-settings";
    id: string;
  };
};

/** details of 422 validation: the problems, by path. */
export type ValidationDetails = {
  issues: {
    path: string;
    message: string;
  }[];
};

/** details of 409 dependency_unapproved: what must be approved first. */
export type DependencyDetails = {
  refs: {
    type: "card-categories" | "cards" | "whoami-subjects" | "box-categories" | "box-questions" | "penalty-questions" | "practice-questions" | "media" | "clubs" | "football-logic" | "put-in-order" | "career-path" | "daily-schedule" | "daily-settings";
    id?: string;
    key?: string;
    puzzle?: string;
    status?: "draft" | "ready" | "approved" | "archived";
  }[];
};

/** The query of a paged list: cursor (the previous page’s nextCursor) and limit (1–200, default 50). */
export type PageQuery = {
  cursor?: string;
  limit?: string;
};

/** GET /admin/players query: q is a nickname prefix (any case), a partner player id or a player id. */
export type PlayerSearchQuery = {
  q: string;
  cursor?: string;
  limit?: string;
};

/** GET /admin/players: matching players by nickname, a page at a time. */
export type AdminPlayerList = {
  items: {
    id: string;
    displayName: string;
    provider: "demo" | "betsson" | "dev" | "load";
    partnerPlayerId: string | null;
    status: "active" | "blocked" | "self_excluded" | "deleted";
    rating: number;
    games: number;
    createdAt: string;
  }[];
  nextCursor: string | null;
};

/** GET /admin/players/:id */
export type AdminPlayer = {
  id: string;
  displayName: string;
  provider: "demo" | "betsson" | "dev" | "load";
  partnerPlayerId: string | null;
  status: "active" | "blocked" | "self_excluded" | "deleted";
  avatar: string | null;
  clubId: string | null;
  createdAt: string;
  lastSeenAt: string | null;
  liveMatchId: string | null;
  rating: {
    rating: number;
    ratingVersion: number;
    games: number;
    wins: number;
    losses: number;
    noContests: number;
    streak: number;
    bestStreak: number;
  };
  tickets: {
    balance: number;
    perDay: number;
    refilledOn: string | null;
  };
  dailies: {
    attempts: number;
    completed: number;
    lastDate: string | null;
    games: {
      footballLogic: {
        attempts: number;
        completed: number;
      };
      putInOrder: {
        attempts: number;
        completed: number;
      };
      careerPath: {
        attempts: number;
        completed: number;
      };
    };
  };
  practice: {
    runs: number;
    bestStreak: number;
    lastRunAt: string | null;
  };
};

/** GET /admin/players/:id/matches: newest first. */
export type AdminPlayerMatchList = {
  items: {
    matchId: string;
    status: "live" | "settled" | "void" | "cancelled";
    createdAt: string;
    settledAt: string | null;
    decidedBy: string | null;
    resultVersion: number;
    seat: "me" | "op";
    outcome: "win" | "loss" | "noContest" | null;
    ratingDelta: number | null;
    ticketRefunded: boolean | null;
    score: {
      mine: number;
      theirs: number;
    } | null;
    opponent: {
      id: string;
      displayName: string;
    };
  }[];
  nextCursor: string | null;
};

/** GET /admin/players/:id/tickets: the ticket ledger, newest first. */
export type AdminLedgerList = {
  items: {
    id: string;
    delta: number;
    reason: "refill" | "spend" | "refund" | "reward" | "admin";
    ref: string;
    balanceAfter: number;
    createdAt: string;
  }[];
  nextCursor: string | null;
};

/** GET /admin/matches/:id, and the answer to a correction. A match voided after Redis lost its state has no inputs (inputs.missing says why). Inputs go to the archive 180 days after the match (inputs.archivedAt) and are read back from it; missing is archived when the archive cannot be read just now, and expired once it is deleted (730 days after the match). */
export type AdminMatchRecord = {
  id: string;
  status: "live" | "settled" | "void" | "cancelled";
  createdAt: string;
  settledAt: string | null;
  decidedBy: string | null;
  score: {
    me: number;
    op: number;
  } | null;
  roundsCompleted: number | null;
  releaseId: string;
  rulesVersion: number;
  stateSchema: number;
  dev: boolean;
  forfeitDay: string | null;
  resultVersion: number;
  correctedAt: string | null;
  inputs: {
    kept: boolean;
    entries: unknown[] | null;
    missing: "redis_lost" | "never_started" | "not_recorded" | "archived" | "expired" | null;
    archivedAt?: string;
  };
  players: {
    seat: "me" | "op";
    playerId: string;
    displayName: string;
    partnerPlayerId: string | null;
    outcome: "win" | "loss" | "noContest" | null;
    ratingDelta: number | null;
    ticketRefunded: boolean | null;
    earlyForfeit: "counted" | "overturned" | null;
    ratingEvents: {
      seq: number;
      deltaRule: number;
      appliedDelta: number;
      ratingAfter: number;
      correctionId: string | null;
      at: string;
    }[];
    tickets: {
      id: string;
      delta: number;
      reason: "refill" | "spend" | "refund" | "reward" | "admin";
      ref: string;
      balanceAfter: number;
      createdAt: string;
    }[];
    deliveries: {
      resultVersion: number;
      createdAt: string;
      attempts: number;
      ackedAt: string | null;
      supersededAt: string | null;
      result: unknown;
    }[];
  }[];
  corrections: {
    id: string;
    resultVersion: number;
    kind: "void" | "win";
    reason: string;
    staff: {
      id: string;
      name: string;
    };
    createdAt: string;
    previous: {
      status: "settled" | "void";
      decidedBy: string;
      winner: string | null;
      players: {
        seat: "me" | "op";
        playerId: string;
        outcome: "win" | "loss" | "noContest";
        ratingDelta: number;
        ticketRefunded: boolean;
      }[];
    };
    result: {
      status: "settled" | "void";
      decidedBy: string;
      winner: string | null;
      players: {
        seat: "me" | "op";
        playerId: string;
        outcome: "win" | "loss" | "noContest";
        ratingDelta: number;
        ticketRefunded: boolean;
      }[];
    };
    penaltiesToReview: {
      playerId: string;
      matchId: string;
      georgiaDate: string;
    }[];
  }[];
  reviews: {
    id: string;
    kind: "penalty";
    playerId: string;
    matchId: string;
    georgiaDate: string;
    source: "correction" | "settlement";
    correctionId: string | null;
    countedThen: number | null;
    countedNow: number;
    createdAt: string;
    status: "open" | "corrected" | "dismissed";
    closedAt: string | null;
    closedBy: {
      id: string;
      name: string;
    } | null;
    closingCorrectionId: string | null;
    note: string | null;
  }[];
};

/** POST /admin/matches/:id/corrections: version is the resultVersion read; a winner must be one of the match’s players. */
export type MatchCorrectionRequest = {
  version: number;
  outcome: {
    kind: "void";
  } | {
    kind: "win";
    winner: string;
  };
  reason: string;
};

/** GET /admin/leaderboard: the live standings. */
export type BoardPage = {
  asOf: string;
  total: number;
  items: {
    rank: number;
    playerId: string;
    partnerPlayerId: string | null;
    displayName: string;
    rating: number;
    games: number;
    wins: number;
    losses: number;
  }[];
  nextCursor: string | null;
};

/** POST /admin/leaderboard/snapshots (betsson_admin and ops). Labels are unique, whatever the case. */
export type SnapshotCreateRequest = {
  label: string;
};

/** A frozen leaderboard: never changed or deleted. */
export type Snapshot = {
  id: string;
  label: string;
  takenAt: string;
  takenBy: {
    id: string;
    name: string;
  } | null;
  players: number;
};

/** GET /admin/leaderboard/snapshots: newest first. */
export type SnapshotList = {
  items: {
    id: string;
    label: string;
    takenAt: string;
    takenBy: {
      id: string;
      name: string;
    } | null;
    players: number;
  }[];
  nextCursor: string | null;
};

/** GET /admin/leaderboard/snapshots/:id: the snapshot and a page of its rows by rank. */
export type SnapshotPage = {
  snapshot: {
    id: string;
    label: string;
    takenAt: string;
    takenBy: {
      id: string;
      name: string;
    } | null;
    players: number;
  };
  items: {
    rank: number;
    playerId: string;
    partnerPlayerId: string | null;
    displayName: string;
    rating: number;
    games: number;
    wins: number;
    losses: number;
  }[];
  nextCursor: string | null;
};

/** A CSV download (text/csv; charset=utf-8): a UTF-8 BOM, a header row, RFC 4180 quoting, and a leading apostrophe on any text cell a spreadsheet could read as a formula. */
export type CsvExport = string;

/** GET /admin/dashboard, in Georgia time (Asia/Tbilisi, UTC+4): today and yesterday; the last 7 and 30 days (today so far and the 6 or 29 days before it; null until the daily rollup has reached every day of the period before yesterday); and a point per day for the last 30, oldest first. */
export type Dashboard = {
  timezone: "Asia/Tbilisi";
  generatedAt: string;
  penaltiesToReview: number;
  today: {
    date: string;
    from: string;
    to: string;
    players: {
      new: number;
      active: number;
    };
    matches: {
      created: number;
      settled: number;
      voided: number;
      corrected: number;
    };
    dailies: {
      footballLogic: {
        attempts: number;
        completed: number;
      };
      putInOrder: {
        attempts: number;
        completed: number;
      };
      careerPath: {
        attempts: number;
        completed: number;
      };
    };
    practice: {
      runs: number;
    };
  };
  yesterday: {
    date: string;
    from: string;
    to: string;
    players: {
      new: number;
      active: number;
    };
    matches: {
      created: number;
      settled: number;
      voided: number;
      corrected: number;
    };
    dailies: {
      footballLogic: {
        attempts: number;
        completed: number;
      };
      putInOrder: {
        attempts: number;
        completed: number;
      };
      careerPath: {
        attempts: number;
        completed: number;
      };
    };
    practice: {
      runs: number;
    };
  };
  last7Days: {
    fromDate: string;
    toDate: string;
    from: string;
    to: string;
    players: {
      new: number;
      active: number;
    };
    matches: {
      created: number;
      settled: number;
      voided: number;
      corrected: number;
    };
    dailies: {
      attempts: number;
      completed: number;
      footballLogic: {
        attempts: number;
        completed: number;
      };
      putInOrder: {
        attempts: number;
        completed: number;
      };
      careerPath: {
        attempts: number;
        completed: number;
      };
    };
    practice: {
      runs: number;
    };
  } | null;
  last30Days: {
    fromDate: string;
    toDate: string;
    from: string;
    to: string;
    players: {
      new: number;
      active: number;
    };
    matches: {
      created: number;
      settled: number;
      voided: number;
      corrected: number;
    };
    dailies: {
      attempts: number;
      completed: number;
      footballLogic: {
        attempts: number;
        completed: number;
      };
      putInOrder: {
        attempts: number;
        completed: number;
      };
      careerPath: {
        attempts: number;
        completed: number;
      };
    };
    practice: {
      runs: number;
    };
  } | null;
  days: {
    date: string;
    activePlayers: number;
    newPlayers: number;
    matchesSettled: number;
    dailiesCompleted: number;
    practiceRuns: number;
  }[];
};

/** GET /admin/settings and the answer to a change (ops only). */
export type Settings = {
  ticketsPerDay: {
    value: number;
    effectiveFrom: string | null;
    today: number;
    version: number;
    updatedAt: string | null;
    updatedBy: {
      id: string;
      name: string;
    } | null;
  };
  maintenance: {
    enabled: boolean;
    version: number;
    updatedAt: string | null;
    updatedBy: {
      id: string;
      name: string;
    } | null;
  };
};

/** PATCH /admin/settings/tickets-per-day: version is the one read (0 if never set). */
export type TicketsPerDayRequest = {
  version: number;
  value: number;
};

/** PATCH /admin/settings/maintenance: version is the one read (0 if never set). */
export type MaintenanceRequest = {
  version: number;
  enabled: boolean;
};

/** A penalty to review: an early self-forfeit penalised under an allowance count a correction later lowered. Closed by a correction of its match, or dismissed. */
export type OpsReview = {
  id: string;
  kind: "penalty";
  playerId: string;
  matchId: string;
  georgiaDate: string;
  source: "correction" | "settlement";
  correctionId: string | null;
  countedThen: number | null;
  countedNow: number;
  createdAt: string;
  status: "open" | "corrected" | "dismissed";
  closedAt: string | null;
  closedBy: {
    id: string;
    name: string;
  } | null;
  closingCorrectionId: string | null;
  note: string | null;
};

/** GET /admin/reviews: newest first. */
export type OpsReviewList = {
  items: {
    id: string;
    kind: "penalty";
    playerId: string;
    matchId: string;
    georgiaDate: string;
    source: "correction" | "settlement";
    correctionId: string | null;
    countedThen: number | null;
    countedNow: number;
    createdAt: string;
    status: "open" | "corrected" | "dismissed";
    closedAt: string | null;
    closedBy: {
      id: string;
      name: string;
    } | null;
    closingCorrectionId: string | null;
    note: string | null;
  }[];
  nextCursor: string | null;
};

/** GET /admin/reviews query: status open (the default) or all, cursor, limit. */
export type ReviewListQuery = {
  status?: "open" | "all";
  cursor?: string;
  limit?: string;
};

/** POST /admin/reviews/:id/dismiss (ops): why the penalty stands. */
export type ReviewDismissRequest = {
  note: string;
};

/** details of 409 revision_conflict on a correction or a setting: current is the record or the settings as they are now. */
export type OpsRevisionConflictDetails = {
  current: unknown;
};

/** An uploaded image in private storage, for a media row to use (MediaData.uploadId, with its width and height). width and height are as displayed (EXIF orientation applied). */
export type MediaUpload = {
  id: string;
  contentType: "image/jpeg" | "image/png" | "image/webp";
  bytes: number;
  width: number;
  height: number;
  sha256: string;
  uploadedBy: {
    id: string | null;
    name: string;
  };
  createdAt: string;
};

/** details of 422 invalid_image: type (not JPEG, PNG or WebP, or not what the Content-Type says), signature (the bytes are not an image of those), trailing_data (more than the image), dimensions (over 4096 pixels a side), animated, decode (it does not decode). */
export type ImageRefusalDetails = {
  reason: "type" | "signature" | "trailing_data" | "too_large" | "dimensions" | "animated" | "decode";
};

/** POST /admin/releases/validate, and a publication’s snapshot: errors refuse a publish, warnings do not. An image needs no credit, licence or source: media.missingRights only counts those without. */
export type ReleaseReport = {
  ok: boolean;
  releaseId: string | null;
  currentReleaseId: string | null;
  unchanged: boolean;
  checkedAt: string;
  from: string;
  days: number;
  errors: {
    code: "schema" | "pool" | "practice" | "dailies" | "image_missing" | "rights_missing" | "image_external" | "storage";
    message: string;
    ref?: {
      type: "card-categories" | "cards" | "whoami-subjects" | "box-categories" | "box-questions" | "penalty-questions" | "practice-questions" | "media" | "clubs" | "football-logic" | "put-in-order" | "career-path" | "daily-schedule" | "daily-settings";
      key: string;
    };
  }[];
  warnings: {
    code: "schema" | "pool" | "practice" | "dailies" | "image_missing" | "rights_missing" | "image_external" | "storage";
    message: string;
    ref?: {
      type: "card-categories" | "cards" | "whoami-subjects" | "box-categories" | "box-questions" | "penalty-questions" | "practice-questions" | "media" | "clubs" | "football-logic" | "put-in-order" | "career-path" | "daily-schedule" | "daily-settings";
      key: string;
    };
  }[];
  pools: {
    cardDecks: {
      ready: number;
      needed: number;
      deckSize: number;
    };
    whoAmI: {
      ready: number;
      needed: number;
      clues: number;
    };
    box: {
      ready: number;
      needed: number;
      questions: number;
    };
    penalties: {
      ready: number;
      needed: number;
    };
    practice: {
      easy: number;
      medium: number;
      hard: number;
      needed: {
        easy: number;
        medium: number;
        hard: number;
      };
    };
  };
  dailies: {
    footballLogic: {
      covered: number;
      missing: string[];
    };
    putInOrder: {
      covered: number;
      missing: string[];
    };
    careerPath: {
      covered: number;
      missing: string[];
    };
  };
  media: {
    images: number;
    uploaded: number;
    external: number;
    missingRights: number;
    pending: number;
  };
  changes: {
    complete: boolean;
    types: {
      type: "card-categories" | "cards" | "whoami-subjects" | "box-categories" | "box-questions" | "penalty-questions" | "practice-questions" | "media" | "clubs" | "football-logic" | "put-in-order" | "career-path" | "daily-schedule" | "daily-settings";
      added: number;
      changed: number;
      removed: number;
    }[];
  };
};

/** POST /admin/releases/publish and POST /admin/releases/:id/rollback: a key the client chose, kept for every retry of this request (a UUID will do). The same key answers the same publication. */
export type PublicationRequest = {
  idemKey: string;
};

/** A publish or a rollback, run in phases on the server (poll GET /admin/publications/:id until status is published or failed). One runs at a time. A publish: snapshot, validate, media, artifact, available, pointer; a rollback: pointer only (the rest skipped). */
export type Publication = {
  id: string;
  kind: "publish" | "rollback";
  status: "running" | "failing" | "published" | "failed";
  phases: {
    name: "snapshot" | "validate" | "media" | "artifact" | "available" | "pointer";
    state: "pending" | "done" | "skipped" | "failed";
  }[];
  releaseId: string | null;
  previousReleaseId: string | null;
  pointerVersion: number | null;
  changed: boolean | null;
  requestedBy: {
    id: string | null;
    name: string;
  };
  requestedAt: string;
  updatedAt: string;
  finishedAt: string | null;
  attempts: number;
  error: {
    code: "validation_failed" | "actor_revoked" | "pointer_moved" | "release_unavailable" | "image_missing" | "storage_failed" | "artifact_conflict" | "gave_up";
    message: string;
  } | null;
  report: {
    ok: boolean;
    releaseId: string | null;
    currentReleaseId: string | null;
    unchanged: boolean;
    checkedAt: string;
    from: string;
    days: number;
    errors: {
      code: "schema" | "pool" | "practice" | "dailies" | "image_missing" | "rights_missing" | "image_external" | "storage";
      message: string;
      ref?: {
        type: "card-categories" | "cards" | "whoami-subjects" | "box-categories" | "box-questions" | "penalty-questions" | "practice-questions" | "media" | "clubs" | "football-logic" | "put-in-order" | "career-path" | "daily-schedule" | "daily-settings";
        key: string;
      };
    }[];
    warnings: {
      code: "schema" | "pool" | "practice" | "dailies" | "image_missing" | "rights_missing" | "image_external" | "storage";
      message: string;
      ref?: {
        type: "card-categories" | "cards" | "whoami-subjects" | "box-categories" | "box-questions" | "penalty-questions" | "practice-questions" | "media" | "clubs" | "football-logic" | "put-in-order" | "career-path" | "daily-schedule" | "daily-settings";
        key: string;
      };
    }[];
    pools: {
      cardDecks: {
        ready: number;
        needed: number;
        deckSize: number;
      };
      whoAmI: {
        ready: number;
        needed: number;
        clues: number;
      };
      box: {
        ready: number;
        needed: number;
        questions: number;
      };
      penalties: {
        ready: number;
        needed: number;
      };
      practice: {
        easy: number;
        medium: number;
        hard: number;
        needed: {
          easy: number;
          medium: number;
          hard: number;
        };
      };
    };
    dailies: {
      footballLogic: {
        covered: number;
        missing: string[];
      };
      putInOrder: {
        covered: number;
        missing: string[];
      };
      careerPath: {
        covered: number;
        missing: string[];
      };
    };
    media: {
      images: number;
      uploaded: number;
      external: number;
      missingRights: number;
      pending: number;
    };
    changes: {
      complete: boolean;
      types: {
        type: "card-categories" | "cards" | "whoami-subjects" | "box-categories" | "box-questions" | "penalty-questions" | "practice-questions" | "media" | "clubs" | "football-logic" | "put-in-order" | "career-path" | "daily-schedule" | "daily-settings";
        added: number;
        changed: number;
        removed: number;
      }[];
    };
  } | null;
  notify: {
    state: "none" | "pending" | "sent" | "gave_up";
    attempts: number;
    at: string | null;
  };
};

/** details of 409 publication_in_progress: the publication holding the slot. */
export type PublicationBusyDetails = {
  publicationId: string;
};

/** GET /admin/releases query: cursor (the previous page’s nextCursor) and limit (1–200, default 50). */
export type ReleaseListQuery = {
  cursor?: string;
  limit?: string;
};

/** GET /admin/releases: the pointer, the publication under way (if any), releases newest first, the latest 50 pointer moves. */
export type ReleaseList = {
  pointer: {
    releaseId: string | null;
    version: number;
    movedAt: string | null;
    movedBy: {
      id: string | null;
      name: string;
    } | null;
  };
  active: {
    id: string;
    kind: "publish" | "rollback";
    status: "running" | "failing" | "published" | "failed";
    phases: {
      name: "snapshot" | "validate" | "media" | "artifact" | "available" | "pointer";
      state: "pending" | "done" | "skipped" | "failed";
    }[];
    releaseId: string | null;
    previousReleaseId: string | null;
    pointerVersion: number | null;
    changed: boolean | null;
    requestedBy: {
      id: string | null;
      name: string;
    };
    requestedAt: string;
    updatedAt: string;
    finishedAt: string | null;
    attempts: number;
    error: {
      code: "validation_failed" | "actor_revoked" | "pointer_moved" | "release_unavailable" | "image_missing" | "storage_failed" | "artifact_conflict" | "gave_up";
      message: string;
    } | null;
    report: {
      ok: boolean;
      releaseId: string | null;
      currentReleaseId: string | null;
      unchanged: boolean;
      checkedAt: string;
      from: string;
      days: number;
      errors: {
        code: "schema" | "pool" | "practice" | "dailies" | "image_missing" | "rights_missing" | "image_external" | "storage";
        message: string;
        ref?: {
          type: "card-categories" | "cards" | "whoami-subjects" | "box-categories" | "box-questions" | "penalty-questions" | "practice-questions" | "media" | "clubs" | "football-logic" | "put-in-order" | "career-path" | "daily-schedule" | "daily-settings";
          key: string;
        };
      }[];
      warnings: {
        code: "schema" | "pool" | "practice" | "dailies" | "image_missing" | "rights_missing" | "image_external" | "storage";
        message: string;
        ref?: {
          type: "card-categories" | "cards" | "whoami-subjects" | "box-categories" | "box-questions" | "penalty-questions" | "practice-questions" | "media" | "clubs" | "football-logic" | "put-in-order" | "career-path" | "daily-schedule" | "daily-settings";
          key: string;
        };
      }[];
      pools: {
        cardDecks: {
          ready: number;
          needed: number;
          deckSize: number;
        };
        whoAmI: {
          ready: number;
          needed: number;
          clues: number;
        };
        box: {
          ready: number;
          needed: number;
          questions: number;
        };
        penalties: {
          ready: number;
          needed: number;
        };
        practice: {
          easy: number;
          medium: number;
          hard: number;
          needed: {
            easy: number;
            medium: number;
            hard: number;
          };
        };
      };
      dailies: {
        footballLogic: {
          covered: number;
          missing: string[];
        };
        putInOrder: {
          covered: number;
          missing: string[];
        };
        careerPath: {
          covered: number;
          missing: string[];
        };
      };
      media: {
        images: number;
        uploaded: number;
        external: number;
        missingRights: number;
        pending: number;
      };
      changes: {
        complete: boolean;
        types: {
          type: "card-categories" | "cards" | "whoami-subjects" | "box-categories" | "box-questions" | "penalty-questions" | "practice-questions" | "media" | "clubs" | "football-logic" | "put-in-order" | "career-path" | "daily-schedule" | "daily-settings";
          added: number;
          changed: number;
          removed: number;
        }[];
      };
    } | null;
    notify: {
      state: "none" | "pending" | "sent" | "gave_up";
      attempts: number;
      at: string | null;
    };
  } | null;
  items: {
    id: string;
    hash: string;
    formatVersion: number;
    status: "available" | "retired";
    createdAt: string;
    createdBy: {
      id: string | null;
      name: string;
    };
    current: boolean;
    wasCurrent: boolean;
    members: number;
    publicationId: string | null;
  }[];
  nextCursor: string | null;
  history: {
    version: number;
    releaseId: string;
    previousReleaseId: string | null;
    movedAt: string;
    movedBy: {
      id: string | null;
      name: string;
    };
  }[];
};

/** GET /admin/releases/:id: what it holds, its rows, and what changed against the release current before it. */
export type ReleaseDetail = {
  release: {
    id: string;
    hash: string;
    formatVersion: number;
    status: "available" | "retired";
    createdAt: string;
    createdBy: {
      id: string | null;
      name: string;
    };
    current: boolean;
    wasCurrent: boolean;
    members: number;
    publicationId: string | null;
  };
  manifest: {
    cards: {
      categories: number;
      cards: number;
    };
    whoAmI: {
      subjects: number;
    };
    box: {
      categories: number;
      questions: number;
    };
    penalties: {
      questions: number;
    };
    dailies: {
      footballLogic: {
        sets: number;
        items: number;
        scheduledDates: number;
        cycle: number;
        coveredDays: number;
      };
      putInOrder: {
        sets: number;
        items: number;
        scheduledDates: number;
        cycle: number;
        coveredDays: number;
      };
      careerPath: {
        sets: number;
        items: number;
        scheduledDates: number;
        cycle: number;
        coveredDays: number;
      };
    };
    practice: {
      easy: number;
      medium: number;
      hard: number;
    };
    clubs: number;
    media: number;
  };
  members: {
    type: "card-categories" | "cards" | "whoami-subjects" | "box-categories" | "box-questions" | "penalty-questions" | "practice-questions" | "media" | "clubs" | "football-logic" | "put-in-order" | "career-path" | "daily-schedule" | "daily-settings";
    id: string;
    label: string;
    contentVersion: number;
  }[];
  diff: {
    against: string;
    complete: boolean;
    types: {
      type: "card-categories" | "cards" | "whoami-subjects" | "box-categories" | "box-questions" | "penalty-questions" | "practice-questions" | "media" | "clubs" | "football-logic" | "put-in-order" | "career-path" | "daily-schedule" | "daily-settings";
      added: {
        type: "card-categories" | "cards" | "whoami-subjects" | "box-categories" | "box-questions" | "penalty-questions" | "practice-questions" | "media" | "clubs" | "football-logic" | "put-in-order" | "career-path" | "daily-schedule" | "daily-settings";
        id: string;
        label: string;
        contentVersion: number;
      }[];
      changed: {
        type: "card-categories" | "cards" | "whoami-subjects" | "box-categories" | "box-questions" | "penalty-questions" | "practice-questions" | "media" | "clubs" | "football-logic" | "put-in-order" | "career-path" | "daily-schedule" | "daily-settings";
        id: string;
        label: string;
        from: number;
        to: number;
      }[];
      removed: {
        type: "card-categories" | "cards" | "whoami-subjects" | "box-categories" | "box-questions" | "penalty-questions" | "practice-questions" | "media" | "clubs" | "football-logic" | "put-in-order" | "career-path" | "daily-schedule" | "daily-settings";
        id: string;
        label: string;
        contentVersion: number;
      }[];
    }[];
  } | null;
};

/** POST /admin/dailies/:game/publish: whole days (puzzles) to publish. Each must have exactly the day size of its game (footballLogic 10, putInOrder 4, careerPath 10) live questions. */
export type DailyPublishRequest = {
  puzzles: string[];
};

/** In one transaction (publisher and up): the days’ questions are approved (each day then has exactly its size of approved questions); today keeps the day players get now (a schedule entry pins it; 503 busy while the current release cannot be read); the calendar is read from approved entries, and a date holding a draft or archived entry gets it back; each day that never had a date gets the next free one after the last; the cycle becomes every dated day in date order, then the days it repeated already (none drops out), anchored the day after the last date, so after the calendar the days repeat from the first. Days already dated never move. Running it again changes nothing. Players get it with the next release. */
export type DailyPublishResponse = {
  game: "footballLogic" | "putInOrder" | "careerPath";
  today: string;
  days: {
    puzzle: string;
    date: string;
  }[];
  cycle: {
    anchor: string;
    sets: string[];
  } | null;
};

/** GET /admin/integration/webhooks query: q (an event id, a partner session id, the partner’s player id or a Table Derby player id), status, cursor, limit. */
export type WebhookListQuery = {
  q?: string;
  status?: "pending" | "sent" | "dead";
  cursor?: string;
  limit?: string;
};

/** POST /admin/integration/webhooks/:id/retry (ops): {} to retry now; retarget: true also moves an event bound to an earlier webhook address to the current one. Either way its 24 hours of retries start again. */
export type WebhookRetryRequest = {
  retarget?: boolean;
};

/** A result event for the partner and where its delivery stands: pending (retried with backoff for 24 hours), sent (the partner answered 2xx) or dead (given up; retry it now to try again). */
export type WebhookEvent = {
  eventId: string;
  type: "score" | "match.settled" | "match.voided" | "match.corrected" | "daily.completed" | "practice.completed";
  partner: string;
  environment: "sandbox" | "production";
  playerId: string;
  userId: string;
  sessionId: string;
  matchId: string | null;
  occurredAt: string;
  enqueuedAt: string;
  status: "pending" | "sent" | "dead";
  attempts: number;
  nextAttemptAt: string | null;
  sending: boolean;
  sentAt: string | null;
  deadAt: string | null;
  revivedAt: string | null;
  lastError: string | null;
  destination: string | null;
  destinationCurrent: boolean;
};

/** GET /admin/integration/webhooks: newest first. */
export type WebhookEventList = {
  items: {
    eventId: string;
    type: "score" | "match.settled" | "match.voided" | "match.corrected" | "daily.completed" | "practice.completed";
    partner: string;
    environment: "sandbox" | "production";
    playerId: string;
    userId: string;
    sessionId: string;
    matchId: string | null;
    occurredAt: string;
    enqueuedAt: string;
    status: "pending" | "sent" | "dead";
    attempts: number;
    nextAttemptAt: string | null;
    sending: boolean;
    sentAt: string | null;
    deadAt: string | null;
    revivedAt: string | null;
    lastError: string | null;
    destination: string | null;
    destinationCurrent: boolean;
  }[];
  nextCursor: string | null;
};

/** One delivery attempt: the HTTP status the partner answered, or why there was no answer (error), its latency and the start of the answer. */
export type WebhookAttempt = {
  attempt: number;
  startedAt: string;
  latencyMs: number | null;
  httpStatus: number | null;
  error: "timeout" | "dns" | "refused" | "reset" | "tls" | "network" | "aborted" | "lease_expired" | null;
  delivered: boolean;
  reason: string | null;
  responseSnippet: string | null;
};

/** The result event exactly as it is sent to the partner (partner contract §4); its data depends on its type. */
export type WebhookEnvelope = {
  eventId: string;
  type: "score" | "match.settled" | "match.voided" | "match.corrected" | "daily.completed" | "practice.completed";
  occurredAt: string;
  sessionId: string;
  playerId: string;
  gameId: string;
  data: unknown;
};

/** GET /admin/integration/webhooks/:id (the event id) and the answer to a retry: the event, the envelope sent and its latest 200 attempts, oldest first. */
export type WebhookEventDetail = {
  event: {
    eventId: string;
    type: "score" | "match.settled" | "match.voided" | "match.corrected" | "daily.completed" | "practice.completed";
    partner: string;
    environment: "sandbox" | "production";
    playerId: string;
    userId: string;
    sessionId: string;
    matchId: string | null;
    occurredAt: string;
    enqueuedAt: string;
    status: "pending" | "sent" | "dead";
    attempts: number;
    nextAttemptAt: string | null;
    sending: boolean;
    sentAt: string | null;
    deadAt: string | null;
    revivedAt: string | null;
    lastError: string | null;
    destination: string | null;
    destinationCurrent: boolean;
  };
  payload: {
    eventId: string;
    type: "score" | "match.settled" | "match.voided" | "match.corrected" | "daily.completed" | "practice.completed";
    occurredAt: string;
    sessionId: string;
    playerId: string;
    gameId: string;
    data: unknown;
  };
  attempts: {
    attempt: number;
    startedAt: string;
    latencyMs: number | null;
    httpStatus: number | null;
    error: "timeout" | "dns" | "refused" | "reset" | "tls" | "network" | "aborted" | "lease_expired" | null;
    delivered: boolean;
    reason: string | null;
    responseSnippet: string | null;
  }[];
};
