// GENERATED from the backend OpenAPI spec, filtered to /api/v1/admin/wl/content/* (the CMS-wide
// api.generated.ts lags the backend; regenerating it wholesale breaks unrelated forms).
// Regenerate: export the spec from backend-node (scripts/export-openapi.ts), filter to the content
// paths + their schemas, then `npx openapi-typescript <filtered.json> -o src/types/wl-content.api.generated.ts`.
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/wl/content/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate + dedupe uploaded WL questions against the pool and every past event (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        questions: {
                            /** @enum {string} */
                            type: "mcq_single" | "true_false" | "input_text" | "countdown_list" | "clue_chain" | "put_in_order" | "imposter_multi_select" | "career_path" | "high_low" | "football_logic" | "missing_xi" | "pass_chain" | "stat_sniper";
                            /** @enum {string} */
                            difficulty: "easy" | "medium" | "hard";
                            /**
                             * @default draft
                             * @enum {string}
                             */
                            status?: "draft" | "published" | "archived";
                            /** @enum {string} */
                            visibility?: "public" | "wl_private";
                            prompt: {
                                [key: string]: string;
                            };
                            explanation?: {
                                [key: string]: string;
                            } | null;
                            payload: {
                                /** @enum {string} */
                                type: "mcq_single";
                                image?: {
                                    /** Format: uri */
                                    url: string;
                                    width: number;
                                    height: number;
                                    aspect_ratio?: string;
                                    /** Format: uri */
                                    source_url?: string | null;
                                    /** @enum {string} */
                                    storage_status?: "stored" | "external_fallback";
                                    storage_error?: string | null;
                                    /** Format: date-time */
                                    storage_attempted_at?: string | null;
                                    title?: string | null;
                                    author?: string | null;
                                    license?: string | null;
                                    /** Format: uri */
                                    license_url?: string | null;
                                    provider?: string | null;
                                };
                                options: {
                                    id: string;
                                    text: {
                                        [key: string]: string;
                                    };
                                    is_correct: boolean;
                                }[];
                            } | {
                                /** @enum {string} */
                                type: "true_false";
                                options: ({
                                    /** @enum {string} */
                                    id: "true";
                                    text: {
                                        [key: string]: string;
                                    };
                                    is_correct: boolean;
                                } | {
                                    /** @enum {string} */
                                    id: "false";
                                    text: {
                                        [key: string]: string;
                                    };
                                    is_correct: boolean;
                                })[];
                            } | {
                                /** @enum {string} */
                                type: "imposter_multi_select";
                                options: {
                                    id: string;
                                    text: {
                                        [key: string]: string;
                                    };
                                    is_correct: boolean;
                                }[];
                            } | {
                                /** @enum {string} */
                                type: "input_text";
                                accepted_answers: {
                                    [key: string]: string;
                                }[];
                                case_sensitive: boolean;
                            } | {
                                /** @enum {string} */
                                type: "countdown_list";
                                prompt: {
                                    [key: string]: string;
                                };
                                answer_groups: {
                                    id: string;
                                    display: {
                                        [key: string]: string;
                                    };
                                    accepted_answers: string[];
                                }[];
                            } | {
                                /** @enum {string} */
                                type: "clue_chain";
                                display_answer: {
                                    [key: string]: string;
                                };
                                accepted_answers: string[];
                                clues: {
                                    /** @enum {string} */
                                    type: "text" | "emoji";
                                    content: {
                                        [key: string]: string;
                                    };
                                }[];
                            } | {
                                /** @enum {string} */
                                type: "put_in_order";
                                prompt: {
                                    [key: string]: string;
                                };
                                /** @enum {string} */
                                direction: "asc" | "desc";
                                items: {
                                    id: string;
                                    label: {
                                        [key: string]: string;
                                    };
                                    details?: {
                                        [key: string]: string;
                                    } | null;
                                    emoji?: string | null;
                                    sort_value: number;
                                }[];
                            } | {
                                /** @enum {string} */
                                type: "career_path";
                                clubs: {
                                    [key: string]: string;
                                }[];
                                display_answer: {
                                    [key: string]: string;
                                };
                                accepted_answers: string[];
                            } | {
                                /** @enum {string} */
                                type: "high_low";
                                stat_label: {
                                    [key: string]: string;
                                };
                                matchups: {
                                    id: string;
                                    left_name: {
                                        [key: string]: string;
                                    };
                                    left_value: number;
                                    right_name: {
                                        [key: string]: string;
                                    };
                                    right_value: number;
                                }[];
                            } | {
                                /** @enum {string} */
                                type: "football_logic";
                                /** Format: uri */
                                image_a_url: string;
                                /** Format: uri */
                                image_b_url: string;
                                display_answer: {
                                    [key: string]: string;
                                };
                                accepted_answers: string[];
                                prompt?: {
                                    [key: string]: string;
                                };
                                explanation?: {
                                    [key: string]: string;
                                } | null;
                            } | {
                                /** @enum {string} */
                                type: "missing_xi";
                                team: {
                                    [key: string]: string;
                                };
                                opponent: {
                                    [key: string]: string;
                                };
                                match_label: {
                                    [key: string]: string;
                                };
                                formation: string;
                                score?: string | null;
                                season?: number | null;
                                slots: {
                                    id: string;
                                    position: string;
                                    number: number | null;
                                    x: number;
                                    y: number;
                                    name: {
                                        [key: string]: string;
                                    };
                                    accepted_answers: string[];
                                    tm_id?: number | null;
                                }[];
                                tm_formation?: string | null;
                                verified?: {
                                    source: string;
                                    matchId?: string | null;
                                    checkedAt: string;
                                } | null;
                            } | {
                                /** @enum {string} */
                                type: "pass_chain";
                                start_tm_id: number;
                                target_tm_id: number;
                                par: number;
                                bridges?: number | null;
                                solution: {
                                    tm_id: number;
                                    /**
                                     * @default club
                                     * @enum {string}
                                     */
                                    kind?: "club" | "manager";
                                    via: {
                                        [key: string]: string;
                                    };
                                }[];
                            } | {
                                /** @enum {string} */
                                type: "stat_sniper";
                                kind: string;
                                prompt: {
                                    [key: string]: string;
                                };
                                unit: {
                                    [key: string]: string;
                                };
                                value: number;
                                min: number;
                                max: number;
                                step: number;
                                source?: {
                                    [key: string]: string | number | boolean | unknown | unknown;
                                } | null;
                            };
                        }[];
                    };
                };
            };
            responses: {
                /** @description Per-row report */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WlContentCheckResponse"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/wl/content/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish uploaded WL questions into the protected pool as a batch (admin, async) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        kind: "true_false" | "put_in_order" | "mcq_single" | "career_path" | "clue_chain";
                        note?: string;
                        /** @default false */
                        sync_to_staging?: boolean;
                        /** @default [] */
                        force_indexes?: number[];
                        questions: {
                            /** @enum {string} */
                            type: "mcq_single" | "true_false" | "input_text" | "countdown_list" | "clue_chain" | "put_in_order" | "imposter_multi_select" | "career_path" | "high_low" | "football_logic" | "missing_xi" | "pass_chain" | "stat_sniper";
                            /** @enum {string} */
                            difficulty: "easy" | "medium" | "hard";
                            /**
                             * @default draft
                             * @enum {string}
                             */
                            status?: "draft" | "published" | "archived";
                            /** @enum {string} */
                            visibility?: "public" | "wl_private";
                            prompt: {
                                [key: string]: string;
                            };
                            explanation?: {
                                [key: string]: string;
                            } | null;
                            payload: {
                                /** @enum {string} */
                                type: "mcq_single";
                                image?: {
                                    /** Format: uri */
                                    url: string;
                                    width: number;
                                    height: number;
                                    aspect_ratio?: string;
                                    /** Format: uri */
                                    source_url?: string | null;
                                    /** @enum {string} */
                                    storage_status?: "stored" | "external_fallback";
                                    storage_error?: string | null;
                                    /** Format: date-time */
                                    storage_attempted_at?: string | null;
                                    title?: string | null;
                                    author?: string | null;
                                    license?: string | null;
                                    /** Format: uri */
                                    license_url?: string | null;
                                    provider?: string | null;
                                };
                                options: {
                                    id: string;
                                    text: {
                                        [key: string]: string;
                                    };
                                    is_correct: boolean;
                                }[];
                            } | {
                                /** @enum {string} */
                                type: "true_false";
                                options: ({
                                    /** @enum {string} */
                                    id: "true";
                                    text: {
                                        [key: string]: string;
                                    };
                                    is_correct: boolean;
                                } | {
                                    /** @enum {string} */
                                    id: "false";
                                    text: {
                                        [key: string]: string;
                                    };
                                    is_correct: boolean;
                                })[];
                            } | {
                                /** @enum {string} */
                                type: "imposter_multi_select";
                                options: {
                                    id: string;
                                    text: {
                                        [key: string]: string;
                                    };
                                    is_correct: boolean;
                                }[];
                            } | {
                                /** @enum {string} */
                                type: "input_text";
                                accepted_answers: {
                                    [key: string]: string;
                                }[];
                                case_sensitive: boolean;
                            } | {
                                /** @enum {string} */
                                type: "countdown_list";
                                prompt: {
                                    [key: string]: string;
                                };
                                answer_groups: {
                                    id: string;
                                    display: {
                                        [key: string]: string;
                                    };
                                    accepted_answers: string[];
                                }[];
                            } | {
                                /** @enum {string} */
                                type: "clue_chain";
                                display_answer: {
                                    [key: string]: string;
                                };
                                accepted_answers: string[];
                                clues: {
                                    /** @enum {string} */
                                    type: "text" | "emoji";
                                    content: {
                                        [key: string]: string;
                                    };
                                }[];
                            } | {
                                /** @enum {string} */
                                type: "put_in_order";
                                prompt: {
                                    [key: string]: string;
                                };
                                /** @enum {string} */
                                direction: "asc" | "desc";
                                items: {
                                    id: string;
                                    label: {
                                        [key: string]: string;
                                    };
                                    details?: {
                                        [key: string]: string;
                                    } | null;
                                    emoji?: string | null;
                                    sort_value: number;
                                }[];
                            } | {
                                /** @enum {string} */
                                type: "career_path";
                                clubs: {
                                    [key: string]: string;
                                }[];
                                display_answer: {
                                    [key: string]: string;
                                };
                                accepted_answers: string[];
                            } | {
                                /** @enum {string} */
                                type: "high_low";
                                stat_label: {
                                    [key: string]: string;
                                };
                                matchups: {
                                    id: string;
                                    left_name: {
                                        [key: string]: string;
                                    };
                                    left_value: number;
                                    right_name: {
                                        [key: string]: string;
                                    };
                                    right_value: number;
                                }[];
                            } | {
                                /** @enum {string} */
                                type: "football_logic";
                                /** Format: uri */
                                image_a_url: string;
                                /** Format: uri */
                                image_b_url: string;
                                display_answer: {
                                    [key: string]: string;
                                };
                                accepted_answers: string[];
                                prompt?: {
                                    [key: string]: string;
                                };
                                explanation?: {
                                    [key: string]: string;
                                } | null;
                            } | {
                                /** @enum {string} */
                                type: "missing_xi";
                                team: {
                                    [key: string]: string;
                                };
                                opponent: {
                                    [key: string]: string;
                                };
                                match_label: {
                                    [key: string]: string;
                                };
                                formation: string;
                                score?: string | null;
                                season?: number | null;
                                slots: {
                                    id: string;
                                    position: string;
                                    number: number | null;
                                    x: number;
                                    y: number;
                                    name: {
                                        [key: string]: string;
                                    };
                                    accepted_answers: string[];
                                    tm_id?: number | null;
                                }[];
                                tm_formation?: string | null;
                                verified?: {
                                    source: string;
                                    matchId?: string | null;
                                    checkedAt: string;
                                } | null;
                            } | {
                                /** @enum {string} */
                                type: "pass_chain";
                                start_tm_id: number;
                                target_tm_id: number;
                                par: number;
                                bridges?: number | null;
                                solution: {
                                    tm_id: number;
                                    /**
                                     * @default club
                                     * @enum {string}
                                     */
                                    kind?: "club" | "manager";
                                    via: {
                                        [key: string]: string;
                                    };
                                }[];
                            } | {
                                /** @enum {string} */
                                type: "stat_sniper";
                                kind: string;
                                prompt: {
                                    [key: string]: string;
                                };
                                unit: {
                                    [key: string]: string;
                                };
                                value: number;
                                min: number;
                                max: number;
                                step: number;
                                source?: {
                                    [key: string]: string | number | boolean | unknown | unknown;
                                } | null;
                            };
                        }[];
                    };
                };
            };
            responses: {
                /** @description Batch accepted; poll the batch for progress */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WlContentImportResponse"];
                    };
                };
                /** @description Rows blocked (errors / unforced duplicates) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/wl/content/batches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent WL content import batches (admin) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Batches */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WlContentBatchesResponse"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/wl/content/batches/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One WL content batch with per-row state (admin) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Batch detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WlContentBatchDetail"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Undo a WL content batch: delete its questions that were never dealt (admin) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Undo outcome */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WlContentUndoResponse"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Batch still processing */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/wl/content/batches/{id}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-draw the coming WL event with this batch's questions first (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: uuid
                         * @description Event to re-draw; defaults to the coming one
                         */
                        tournament_id?: string;
                    };
                };
            };
            responses: {
                /** @description Schedule outcome */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WlContentScheduleResponse"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Batch not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Batch not published, no coming event, or play has started */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/wl/content/runway": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fresh editor inventory vs. drawable WL stock per round kind (admin) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Runway */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WlContentRunway"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/wl/content/next-event": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Frozen content of the coming WL event, per game and round (admin) */
        get: {
            parameters: {
                query?: {
                    /** @description Event to show; defaults to the coming one */
                    tournament_id?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Next event content */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WlContentNextEventResponse"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/wl/content/lineup/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Weekends a lineup can be uploaded for, with lock reasons (admin) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WlLineupEventsResponse"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/wl/content/lineup/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate a lineup upload and preview its exact placements; returns a preview id when it can be saved (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        tournament_id: string;
                        /** @enum {string} */
                        scope: "game_0" | "game_1" | "game_2" | "game_3" | "saturday" | "weekend";
                        note?: string | null;
                        questions: {
                            /** @enum {string} */
                            type: "mcq_single" | "true_false" | "input_text" | "countdown_list" | "clue_chain" | "put_in_order" | "imposter_multi_select" | "career_path" | "high_low" | "football_logic" | "missing_xi" | "pass_chain" | "stat_sniper";
                            /** @enum {string} */
                            difficulty: "easy" | "medium" | "hard";
                            /**
                             * @default draft
                             * @enum {string}
                             */
                            status?: "draft" | "published" | "archived";
                            /** @enum {string} */
                            visibility?: "public" | "wl_private";
                            prompt: {
                                [key: string]: string;
                            };
                            explanation?: {
                                [key: string]: string;
                            } | null;
                            payload: {
                                /** @enum {string} */
                                type: "mcq_single";
                                image?: {
                                    /** Format: uri */
                                    url: string;
                                    width: number;
                                    height: number;
                                    aspect_ratio?: string;
                                    /** Format: uri */
                                    source_url?: string | null;
                                    /** @enum {string} */
                                    storage_status?: "stored" | "external_fallback";
                                    storage_error?: string | null;
                                    /** Format: date-time */
                                    storage_attempted_at?: string | null;
                                    title?: string | null;
                                    author?: string | null;
                                    license?: string | null;
                                    /** Format: uri */
                                    license_url?: string | null;
                                    provider?: string | null;
                                };
                                options: {
                                    id: string;
                                    text: {
                                        [key: string]: string;
                                    };
                                    is_correct: boolean;
                                }[];
                            } | {
                                /** @enum {string} */
                                type: "true_false";
                                options: ({
                                    /** @enum {string} */
                                    id: "true";
                                    text: {
                                        [key: string]: string;
                                    };
                                    is_correct: boolean;
                                } | {
                                    /** @enum {string} */
                                    id: "false";
                                    text: {
                                        [key: string]: string;
                                    };
                                    is_correct: boolean;
                                })[];
                            } | {
                                /** @enum {string} */
                                type: "imposter_multi_select";
                                options: {
                                    id: string;
                                    text: {
                                        [key: string]: string;
                                    };
                                    is_correct: boolean;
                                }[];
                            } | {
                                /** @enum {string} */
                                type: "input_text";
                                accepted_answers: {
                                    [key: string]: string;
                                }[];
                                case_sensitive: boolean;
                            } | {
                                /** @enum {string} */
                                type: "countdown_list";
                                prompt: {
                                    [key: string]: string;
                                };
                                answer_groups: {
                                    id: string;
                                    display: {
                                        [key: string]: string;
                                    };
                                    accepted_answers: string[];
                                }[];
                            } | {
                                /** @enum {string} */
                                type: "clue_chain";
                                display_answer: {
                                    [key: string]: string;
                                };
                                accepted_answers: string[];
                                clues: {
                                    /** @enum {string} */
                                    type: "text" | "emoji";
                                    content: {
                                        [key: string]: string;
                                    };
                                }[];
                            } | {
                                /** @enum {string} */
                                type: "put_in_order";
                                prompt: {
                                    [key: string]: string;
                                };
                                /** @enum {string} */
                                direction: "asc" | "desc";
                                items: {
                                    id: string;
                                    label: {
                                        [key: string]: string;
                                    };
                                    details?: {
                                        [key: string]: string;
                                    } | null;
                                    emoji?: string | null;
                                    sort_value: number;
                                }[];
                            } | {
                                /** @enum {string} */
                                type: "career_path";
                                clubs: {
                                    [key: string]: string;
                                }[];
                                display_answer: {
                                    [key: string]: string;
                                };
                                accepted_answers: string[];
                            } | {
                                /** @enum {string} */
                                type: "high_low";
                                stat_label: {
                                    [key: string]: string;
                                };
                                matchups: {
                                    id: string;
                                    left_name: {
                                        [key: string]: string;
                                    };
                                    left_value: number;
                                    right_name: {
                                        [key: string]: string;
                                    };
                                    right_value: number;
                                }[];
                            } | {
                                /** @enum {string} */
                                type: "football_logic";
                                /** Format: uri */
                                image_a_url: string;
                                /** Format: uri */
                                image_b_url: string;
                                display_answer: {
                                    [key: string]: string;
                                };
                                accepted_answers: string[];
                                prompt?: {
                                    [key: string]: string;
                                };
                                explanation?: {
                                    [key: string]: string;
                                } | null;
                            } | {
                                /** @enum {string} */
                                type: "missing_xi";
                                team: {
                                    [key: string]: string;
                                };
                                opponent: {
                                    [key: string]: string;
                                };
                                match_label: {
                                    [key: string]: string;
                                };
                                formation: string;
                                score?: string | null;
                                season?: number | null;
                                slots: {
                                    id: string;
                                    position: string;
                                    number: number | null;
                                    x: number;
                                    y: number;
                                    name: {
                                        [key: string]: string;
                                    };
                                    accepted_answers: string[];
                                    tm_id?: number | null;
                                }[];
                                tm_formation?: string | null;
                                verified?: {
                                    source: string;
                                    matchId?: string | null;
                                    checkedAt: string;
                                } | null;
                            } | {
                                /** @enum {string} */
                                type: "pass_chain";
                                start_tm_id: number;
                                target_tm_id: number;
                                par: number;
                                bridges?: number | null;
                                solution: {
                                    tm_id: number;
                                    /**
                                     * @default club
                                     * @enum {string}
                                     */
                                    kind?: "club" | "manager";
                                    via: {
                                        [key: string]: string;
                                    };
                                }[];
                            } | {
                                /** @enum {string} */
                                type: "stat_sniper";
                                kind: string;
                                prompt: {
                                    [key: string]: string;
                                };
                                unit: {
                                    [key: string]: string;
                                };
                                value: number;
                                min: number;
                                max: number;
                                step: number;
                                source?: {
                                    [key: string]: string | number | boolean | unknown | unknown;
                                } | null;
                            };
                        }[];
                        slots: {
                            game_index: number;
                            round_index: number | null;
                            question_index: number | null;
                            reserve_ordinal: number;
                        }[];
                        lines?: (number | null)[];
                        /** @default [] */
                        force_indexes?: number[];
                    };
                };
            };
            responses: {
                /** @description Preview */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WlLineupPreviewResponse"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Weekend not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/wl/content/lineup/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save a previewed lineup: publishes its questions and places them exactly as previewed, or nothing (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        preview_id: string;
                    };
                };
            };
            responses: {
                /** @description Saving started (poll the batch) */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WlLineupSaveResponse"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Preview not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Preview expired, weekend changed or locked */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/wl/content/tournaments/{id}/reseed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Re-draw a not-yet-played tournament's content from the current pool (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Reseed outcome */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["WlContentReseedResponse"];
                    };
                };
                /** @description Not authenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Not an admin */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                /** @description Play started or wrong status */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorResponse: {
            /** @example VALIDATION_ERROR */
            code: string;
            /** @example Validation failed */
            message: string;
            details?: unknown;
            /** @example uuid-here */
            request_id: string | null;
        };
        WlContentBatch: {
            /** Format: uuid */
            id: string;
            created_at: string;
            /** Format: uuid */
            created_by: string | null;
            created_by_email: string | null;
            kind: string;
            note: string | null;
            /** @enum {string} */
            status: "processing" | "done" | "failed" | "undoing" | "undone";
            row_count: number;
            sync_to_staging: boolean;
            result: {
                [key: string]: unknown;
            } | null;
            error: string | null;
            undone_at: string | null;
            counts: {
                pending: number;
                created: number;
                translated: number;
                published: number;
                failed: number;
                deleted: number;
            };
        };
        WlContentBatchDetail: {
            /** Format: uuid */
            id: string;
            created_at: string;
            /** Format: uuid */
            created_by: string | null;
            created_by_email: string | null;
            kind: string;
            note: string | null;
            /** @enum {string} */
            status: "processing" | "done" | "failed" | "undoing" | "undone";
            row_count: number;
            sync_to_staging: boolean;
            result: {
                [key: string]: unknown;
            } | null;
            error: string | null;
            undone_at: string | null;
            counts: {
                pending: number;
                created: number;
                translated: number;
                published: number;
                failed: number;
                deleted: number;
            };
            rows: {
                row_index: number;
                /** Format: uuid */
                question_id: string | null;
                /** @enum {string} */
                state: "pending" | "created" | "translated" | "published" | "failed" | "deleted";
                error: string | null;
                summary: string;
                placements: {
                    week_key: string;
                    status: string;
                    game_index: number;
                    round_index: number | null;
                    question_index: number | null;
                    reserve_ordinal: number;
                    kind: string;
                }[];
                in_backup: boolean;
            }[];
            lineup: {
                /** Format: uuid */
                tournament_id: string;
                week_key: string;
                games: number[];
                at: string;
                slots: {
                    game_index: number;
                    round_index: number | null;
                    question_index: number | null;
                    reserve_ordinal: number;
                    kind: string;
                    /** @enum {string} */
                    origin: "upload" | "pool";
                    /** Format: uuid */
                    source_question_id: string;
                    summary: string;
                    current: boolean;
                }[];
            } | null;
        };
        WlContentBatchesResponse: {
            batches: components["schemas"]["WlContentBatch"][];
        };
        WlContentCheckResponse: {
            rows: {
                index: number;
                type: string;
                /** @enum {string} */
                status: "ready" | "warning" | "duplicate" | "played" | "error";
                issues: {
                    code: string;
                    message: string;
                    /** @enum {string} */
                    severity: "error" | "warning";
                }[];
                duplicate_of: {
                    /** Format: uuid */
                    question_id: string | null;
                    /** @enum {string} */
                    where: "pool" | "public" | "history" | "batch";
                    played: boolean;
                    week_key: string | null;
                    status: string | null;
                } | null;
                similar_to: {
                    /** Format: uuid */
                    question_id: string | null;
                    /** @enum {string} */
                    where: "pool" | "public" | "history" | "batch";
                    week_key: string | null;
                } | null;
                crests: {
                    club: string;
                    club_id: string | null;
                    logo_url: string | null;
                }[];
                image: {
                    ok: boolean;
                    url: string;
                    width: number | null;
                    height: number | null;
                    bytes: number | null;
                    content_type: string | null;
                    reason: string | null;
                } | null;
            }[];
            staging_configured: boolean;
            summary: {
                ready: number;
                warning: number;
                duplicate: number;
                played: number;
                error: number;
            };
        };
        WlContentImportResponse: {
            /** Format: uuid */
            batch_id: string;
            accepted: number;
        };
        WlContentNextEventResponse: Record<string, never>;
        WlContentReseedResponse: {
            ok: boolean;
            inserted: number;
            previous_rows: number;
            shortages?: {
                [key: string]: {
                    need: number;
                    have: number;
                };
            };
            /** Format: uuid */
            reseed_id: string | null;
        };
        WlContentRunway: {
            need_per_event: {
                [key: string]: number;
            };
            inventory: {
                type: string;
                difficulty: string;
                photo: boolean;
                fresh: number;
            }[];
            drawable: {
                kind: string;
                drawable: number;
                need: number;
                events_left: number;
            }[];
            fresh_events_left: {
                [key: string]: number;
            };
        };
        WlContentScheduleResponse: {
            ok: boolean;
            inserted: number;
            previous_rows: number;
            shortages?: {
                [key: string]: {
                    need: number;
                    have: number;
                };
            };
            /** Format: uuid */
            reseed_id: string | null;
            week_key: string;
            placed_main: number;
            placed_reserve: number;
            not_placed: number;
        };
        WlContentUndoResponse: {
            deleted: number;
            kept: number;
            kept_ids: string[];
            staging_deleted: number | null;
            /** @description Stored photos removed by this undo; null while the cleanup waits behind a running import */
            photos: {
                deleted: number;
                shared: number;
                error: string | null;
            } | null;
        };
        WlLineupEventsResponse: {
            events: {
                /** Format: uuid */
                id: string;
                week_key: string;
                status: string;
                answers: number;
                editable: boolean;
                reason: string | null;
                games: {
                    game_index: number;
                    rows: number;
                    complete: boolean;
                }[];
            }[];
        };
        WlLineupPreviewResponse: {
            /** Format: uuid */
            preview_id: string | null;
            expires_at: string | null;
            event: {
                /** Format: uuid */
                id: string;
                week_key: string;
                status: string;
            };
            scope: string;
            games: number[];
            kept_games: number[];
            slots: {
                game_index: number;
                round_index: number | null;
                question_index: number | null;
                reserve_ordinal: number;
                kind: string;
                /** @enum {string} */
                origin: "upload" | "pool";
                row_index: number | null;
                view: Record<string, never> | null;
            }[];
            replaced: {
                game_index: number;
                rows: Record<string, never>[];
            }[];
            checks: {
                rows: {
                    index: number;
                    type: string;
                    /** @enum {string} */
                    status: "ready" | "warning" | "duplicate" | "played" | "error";
                    issues: {
                        code: string;
                        message: string;
                        /** @enum {string} */
                        severity: "error" | "warning";
                    }[];
                    duplicate_of: {
                        /** Format: uuid */
                        question_id: string | null;
                        /** @enum {string} */
                        where: "pool" | "public" | "history" | "batch";
                        played: boolean;
                        week_key: string | null;
                        status: string | null;
                    } | null;
                    similar_to: {
                        /** Format: uuid */
                        question_id: string | null;
                        /** @enum {string} */
                        where: "pool" | "public" | "history" | "batch";
                        week_key: string | null;
                    } | null;
                    crests: {
                        club: string;
                        club_id: string | null;
                        logo_url: string | null;
                    }[];
                    image: {
                        ok: boolean;
                        url: string;
                        width: number | null;
                        height: number | null;
                        bytes: number | null;
                        content_type: string | null;
                        reason: string | null;
                    } | null;
                }[];
                staging_configured: boolean;
                summary: {
                    ready: number;
                    warning: number;
                    duplicate: number;
                    played: number;
                    error: number;
                };
            };
            problems: {
                where: string;
                message: string;
                row_index: number | null;
            }[];
            undecided: number[];
        };
        WlLineupSaveResponse: {
            /** Format: uuid */
            batch_id: string;
            accepted: number;
            already_started: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
